// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumen/pqc/v1/pqc.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AccountPQC struct {
	Addr       string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty" yaml:"addr"`
	Scheme     string `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty" yaml:"scheme"`
	PubKeyHash []byte `protobuf:"bytes,3,opt,name=pub_key_hash,json=pubKeyHash,proto3" json:"pub_key_hash,omitempty" yaml:"pub_key_hash"`
	AddedAt    int64  `protobuf:"varint,4,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty" yaml:"added_at"`
}

func (m *AccountPQC) Reset()         { *m = AccountPQC{} }
func (m *AccountPQC) String() string { return proto.CompactTextString(m) }
func (*AccountPQC) ProtoMessage()    {}
func (*AccountPQC) Descriptor() ([]byte, []int) {
	return fileDescriptor_904985a3857b2327, []int{0}
}
func (m *AccountPQC) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountPQC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountPQC.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountPQC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPQC.Merge(m, src)
}
func (m *AccountPQC) XXX_Size() int {
	return m.Size()
}
func (m *AccountPQC) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPQC.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPQC proto.InternalMessageInfo

func (m *AccountPQC) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *AccountPQC) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *AccountPQC) GetPubKeyHash() []byte {
	if m != nil {
		return m.PubKeyHash
	}
	return nil
}

func (m *AccountPQC) GetAddedAt() int64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

type PQCSignatureEntry struct {
	Addr      string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Scheme    string `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey    []byte `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (m *PQCSignatureEntry) Reset()         { *m = PQCSignatureEntry{} }
func (m *PQCSignatureEntry) String() string { return proto.CompactTextString(m) }
func (*PQCSignatureEntry) ProtoMessage()    {}
func (*PQCSignatureEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_904985a3857b2327, []int{1}
}
func (m *PQCSignatureEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PQCSignatureEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PQCSignatureEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PQCSignatureEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PQCSignatureEntry.Merge(m, src)
}
func (m *PQCSignatureEntry) XXX_Size() int {
	return m.Size()
}
func (m *PQCSignatureEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PQCSignatureEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PQCSignatureEntry proto.InternalMessageInfo

func (m *PQCSignatureEntry) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *PQCSignatureEntry) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *PQCSignatureEntry) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PQCSignatureEntry) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type PQCSignatures struct {
	Signatures []PQCSignatureEntry `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures"`
}

func (m *PQCSignatures) Reset()         { *m = PQCSignatures{} }
func (m *PQCSignatures) String() string { return proto.CompactTextString(m) }
func (*PQCSignatures) ProtoMessage()    {}
func (*PQCSignatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_904985a3857b2327, []int{2}
}
func (m *PQCSignatures) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PQCSignatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PQCSignatures.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PQCSignatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PQCSignatures.Merge(m, src)
}
func (m *PQCSignatures) XXX_Size() int {
	return m.Size()
}
func (m *PQCSignatures) XXX_DiscardUnknown() {
	xxx_messageInfo_PQCSignatures.DiscardUnknown(m)
}

var xxx_messageInfo_PQCSignatures proto.InternalMessageInfo

func (m *PQCSignatures) GetSignatures() []PQCSignatureEntry {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountPQC)(nil), "lumen.pqc.v1.AccountPQC")
	proto.RegisterType((*PQCSignatureEntry)(nil), "lumen.pqc.v1.PQCSignatureEntry")
	proto.RegisterType((*PQCSignatures)(nil), "lumen.pqc.v1.PQCSignatures")
}

func init() { proto.RegisterFile("lumen/pqc/v1/pqc.proto", fileDescriptor_904985a3857b2327) }

var fileDescriptor_904985a3857b2327 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdf, 0x4a, 0xc2, 0x50,
	0x1c, 0xc7, 0x77, 0x72, 0x4d, 0x3d, 0x4e, 0xcc, 0x63, 0xe8, 0x88, 0xd8, 0xc6, 0xe9, 0x66, 0x11,
	0x4c, 0xac, 0xab, 0xba, 0x73, 0x22, 0x44, 0xdd, 0xe8, 0x82, 0x2e, 0xba, 0x91, 0xb9, 0x1d, 0x5c,
	0xa4, 0xdb, 0xda, 0x1f, 0x69, 0x6f, 0xd1, 0x63, 0x79, 0x13, 0x78, 0xd9, 0xd5, 0x08, 0x7d, 0x83,
	0x3d, 0x41, 0xec, 0xcc, 0x6c, 0xd1, 0xd5, 0x0e, 0xdf, 0x3f, 0xec, 0xf3, 0xe3, 0x0b, 0xdb, 0xf3,
	0x68, 0x41, 0x9c, 0xae, 0xf7, 0x6a, 0x76, 0x97, 0xbd, 0xec, 0xa3, 0x7a, 0xbe, 0x1b, 0xba, 0x88,
	0xa7, 0xba, 0x9a, 0x09, 0xcb, 0xde, 0xc9, 0xf1, 0xcc, 0x9d, 0xb9, 0xd4, 0xe8, 0x66, 0xaf, 0x3c,
	0x83, 0x3f, 0x00, 0x84, 0x7d, 0xd3, 0x74, 0x23, 0x27, 0x1c, 0x8d, 0x07, 0xe8, 0x0c, 0xb2, 0x86,
	0x65, 0xf9, 0x02, 0x90, 0x81, 0x52, 0xd5, 0x1a, 0x69, 0x22, 0xd5, 0x62, 0x63, 0x31, 0xbf, 0xc1,
	0x99, 0x8a, 0x75, 0x6a, 0xa2, 0x73, 0xc8, 0x05, 0xa6, 0x4d, 0x16, 0x44, 0x38, 0xa0, 0xb1, 0x66,
	0x9a, 0x48, 0xf5, 0x3c, 0x96, 0xeb, 0x58, 0xdf, 0x05, 0xd0, 0x35, 0xe4, 0xbd, 0x68, 0x3a, 0x79,
	0x21, 0xf1, 0xc4, 0x36, 0x02, 0x5b, 0x28, 0xc9, 0x40, 0xe1, 0xb5, 0x4e, 0x9a, 0x48, 0xad, 0xbc,
	0x50, 0x74, 0xb1, 0x0e, 0xbd, 0x68, 0x7a, 0x4f, 0xe2, 0x5b, 0x23, 0xb0, 0x91, 0x0a, 0x2b, 0x86,
	0x65, 0x11, 0x6b, 0x62, 0x84, 0x02, 0x2b, 0x03, 0xa5, 0xa4, 0xb5, 0xd2, 0x44, 0x6a, 0xec, 0x71,
	0xa8, 0x83, 0xf5, 0x32, 0x7d, 0xf6, 0xc3, 0x3b, 0xb6, 0x72, 0x78, 0xc4, 0xe1, 0x25, 0x6c, 0x8e,
	0xc6, 0x83, 0x87, 0xe7, 0x99, 0x63, 0x84, 0x91, 0x4f, 0x86, 0x4e, 0xe8, 0xc7, 0x08, 0x15, 0xaf,
	0xda, 0x1d, 0xd1, 0xfe, 0x7b, 0xc4, 0x9e, 0xf8, 0x14, 0x56, 0x83, 0x9f, 0x76, 0x8e, 0xab, 0xff,
	0x0a, 0xa8, 0x03, 0xcb, 0x3b, 0x62, 0xca, 0xc4, 0xeb, 0x5c, 0x4e, 0x8c, 0x1f, 0x61, 0xbd, 0xf8,
	0xdf, 0x00, 0x0d, 0x21, 0xdc, 0xd7, 0x02, 0x01, 0xc8, 0x25, 0xa5, 0x76, 0x29, 0xa9, 0xc5, 0x45,
	0xd4, 0x7f, 0xa0, 0x1a, 0xbb, 0x4a, 0x24, 0x46, 0x2f, 0x14, 0xb5, 0x8b, 0xd5, 0x46, 0x04, 0xeb,
	0x8d, 0x08, 0xbe, 0x36, 0x22, 0x78, 0xdf, 0x8a, 0xcc, 0x7a, 0x2b, 0x32, 0x9f, 0x5b, 0x91, 0x79,
	0x6a, 0xe6, 0xab, 0xbf, 0xd1, 0xdd, 0xc3, 0xd8, 0x23, 0xc1, 0x94, 0xa3, 0x9b, 0x5e, 0x7d, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x7e, 0x9b, 0x9a, 0xae, 0x11, 0x02, 0x00, 0x00,
}

func (m *AccountPQC) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountPQC) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountPQC) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AddedAt != 0 {
		i = encodeVarintPqc(dAtA, i, uint64(m.AddedAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PubKeyHash) > 0 {
		i -= len(m.PubKeyHash)
		copy(dAtA[i:], m.PubKeyHash)
		i = encodeVarintPqc(dAtA, i, uint64(len(m.PubKeyHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Scheme) > 0 {
		i -= len(m.Scheme)
		copy(dAtA[i:], m.Scheme)
		i = encodeVarintPqc(dAtA, i, uint64(len(m.Scheme)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintPqc(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PQCSignatureEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PQCSignatureEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PQCSignatureEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintPqc(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintPqc(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Scheme) > 0 {
		i -= len(m.Scheme)
		copy(dAtA[i:], m.Scheme)
		i = encodeVarintPqc(dAtA, i, uint64(len(m.Scheme)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintPqc(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PQCSignatures) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PQCSignatures) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PQCSignatures) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signatures[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPqc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintPqc(dAtA []byte, offset int, v uint64) int {
	offset -= sovPqc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AccountPQC) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovPqc(uint64(l))
	}
	l = len(m.Scheme)
	if l > 0 {
		n += 1 + l + sovPqc(uint64(l))
	}
	l = len(m.PubKeyHash)
	if l > 0 {
		n += 1 + l + sovPqc(uint64(l))
	}
	if m.AddedAt != 0 {
		n += 1 + sovPqc(uint64(m.AddedAt))
	}
	return n
}

func (m *PQCSignatureEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovPqc(uint64(l))
	}
	l = len(m.Scheme)
	if l > 0 {
		n += 1 + l + sovPqc(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovPqc(uint64(l))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovPqc(uint64(l))
	}
	return n
}

func (m *PQCSignatures) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovPqc(uint64(l))
		}
	}
	return n
}

func sovPqc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPqc(x uint64) (n int) {
	return sovPqc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccountPQC) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPqc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountPQC: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountPQC: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPqc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPqc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scheme", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPqc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPqc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scheme = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPqc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPqc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKeyHash = append(m.PubKeyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKeyHash == nil {
				m.PubKeyHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedAt", wireType)
			}
			m.AddedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AddedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPqc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPqc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PQCSignatureEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPqc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PQCSignatureEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PQCSignatureEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPqc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPqc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scheme", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPqc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPqc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scheme = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPqc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPqc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPqc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPqc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = append(m.PubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKey == nil {
				m.PubKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPqc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPqc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PQCSignatures) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPqc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PQCSignatures: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PQCSignatures: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPqc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPqc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, PQCSignatureEntry{})
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPqc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPqc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPqc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPqc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPqc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPqc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPqc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPqc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPqc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPqc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPqc = fmt.Errorf("proto: unexpected end of group")
)
