// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumen/tokenomics/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	TxTaxRate                  string `protobuf:"bytes,1,opt,name=tx_tax_rate,json=txTaxRate,proto3" json:"tx_tax_rate,omitempty"`
	InitialRewardPerBlockLumn  uint64 `protobuf:"varint,2,opt,name=initial_reward_per_block_lumn,json=initialRewardPerBlockLumn,proto3" json:"initial_reward_per_block_lumn,omitempty"`
	HalvingIntervalBlocks      uint64 `protobuf:"varint,3,opt,name=halving_interval_blocks,json=halvingIntervalBlocks,proto3" json:"halving_interval_blocks,omitempty"`
	SupplyCapLumn              uint64 `protobuf:"varint,4,opt,name=supply_cap_lumn,json=supplyCapLumn,proto3" json:"supply_cap_lumn,omitempty"`
	Decimals                   uint32 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	MinSendUlmn                uint64 `protobuf:"varint,6,opt,name=min_send_ulmn,json=minSendUlmn,proto3" json:"min_send_ulmn,omitempty"`
	Denom                      string `protobuf:"bytes,7,opt,name=denom,proto3" json:"denom,omitempty"`
	DistributionIntervalBlocks uint64 `protobuf:"varint,8,opt,name=distribution_interval_blocks,json=distributionIntervalBlocks,proto3" json:"distribution_interval_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac85b480dd46663e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTxTaxRate() string {
	if m != nil {
		return m.TxTaxRate
	}
	return ""
}

func (m *Params) GetInitialRewardPerBlockLumn() uint64 {
	if m != nil {
		return m.InitialRewardPerBlockLumn
	}
	return 0
}

func (m *Params) GetHalvingIntervalBlocks() uint64 {
	if m != nil {
		return m.HalvingIntervalBlocks
	}
	return 0
}

func (m *Params) GetSupplyCapLumn() uint64 {
	if m != nil {
		return m.SupplyCapLumn
	}
	return 0
}

func (m *Params) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *Params) GetMinSendUlmn() uint64 {
	if m != nil {
		return m.MinSendUlmn
	}
	return 0
}

func (m *Params) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Params) GetDistributionIntervalBlocks() uint64 {
	if m != nil {
		return m.DistributionIntervalBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "lumen.tokenomics.v1.Params")
}

func init() { proto.RegisterFile("lumen/tokenomics/v1/params.proto", fileDescriptor_ac85b480dd46663e) }

var fileDescriptor_ac85b480dd46663e = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbd, 0xce, 0x12, 0x41,
	0x14, 0x86, 0x19, 0x3f, 0x40, 0x18, 0x42, 0x8c, 0x23, 0xc6, 0x65, 0xa3, 0xeb, 0x86, 0xc2, 0x10,
	0x0b, 0x36, 0x68, 0x62, 0x61, 0x45, 0xb0, 0x32, 0xb1, 0x20, 0xab, 0x36, 0x36, 0x93, 0x61, 0x77,
	0x82, 0x13, 0xe6, 0x2f, 0x33, 0xb3, 0xeb, 0x72, 0x03, 0x16, 0x56, 0x5e, 0x82, 0x97, 0xe0, 0x65,
	0x58, 0x52, 0x5a, 0x1a, 0x28, 0xf4, 0x32, 0x0c, 0x33, 0x44, 0x31, 0x7e, 0xcd, 0xe6, 0xfc, 0x3c,
	0xef, 0xbb, 0x67, 0xce, 0x81, 0x29, 0xaf, 0x04, 0x95, 0x99, 0x53, 0x5b, 0x2a, 0x95, 0x60, 0x85,
	0xcd, 0xea, 0x79, 0xa6, 0x89, 0x21, 0xc2, 0xce, 0xb4, 0x51, 0x4e, 0xa1, 0x3b, 0x9e, 0x98, 0xfd,
	0x25, 0x66, 0xf5, 0x3c, 0xbe, 0x4d, 0x04, 0x93, 0x2a, 0xf3, 0xdf, 0xc0, 0xc5, 0xa3, 0x8d, 0xda,
	0x28, 0x1f, 0x66, 0xa7, 0x28, 0x54, 0x27, 0x1f, 0xaf, 0x60, 0x77, 0xe5, 0xed, 0x50, 0x02, 0x07,
	0xae, 0xc1, 0x8e, 0x34, 0xd8, 0x10, 0x47, 0x23, 0x90, 0x82, 0x69, 0x3f, 0xef, 0xbb, 0xe6, 0x0d,
	0x69, 0x72, 0xe2, 0x28, 0x5a, 0xc0, 0x07, 0x4c, 0x32, 0xc7, 0x08, 0xc7, 0x86, 0x7e, 0x20, 0xa6,
	0xc4, 0x9a, 0x1a, 0xbc, 0xe6, 0xaa, 0xd8, 0x62, 0x5e, 0x09, 0x19, 0xdd, 0x48, 0xc1, 0xb4, 0x9d,
	0x8f, 0xcf, 0x50, 0xee, 0x99, 0x15, 0x35, 0xcb, 0x13, 0xf1, 0xaa, 0x12, 0x12, 0x3d, 0x83, 0xf7,
	0xde, 0x13, 0x5e, 0x33, 0xb9, 0xc1, 0x4c, 0x3a, 0x6a, 0x6a, 0xc2, 0x83, 0xde, 0x46, 0x57, 0x5e,
	0x7b, 0xf7, 0xdc, 0x7e, 0x79, 0xee, 0x7a, 0xa9, 0x45, 0x8f, 0xe0, 0x2d, 0x5b, 0x69, 0xcd, 0x77,
	0xb8, 0x20, 0x3a, 0xfc, 0xab, 0xed, 0xf9, 0x61, 0x28, 0xbf, 0x20, 0xda, 0xfb, 0xc7, 0xb0, 0x57,
	0xd2, 0x82, 0x09, 0xc2, 0x6d, 0xd4, 0x49, 0xc1, 0x74, 0x98, 0xff, 0xc9, 0xd1, 0x04, 0x0e, 0x05,
	0x93, 0xd8, 0x52, 0x59, 0xe2, 0x8a, 0x0b, 0x19, 0x75, 0xbd, 0xc3, 0x40, 0x30, 0xf9, 0x9a, 0xca,
	0xf2, 0x2d, 0x17, 0x12, 0x8d, 0x60, 0xa7, 0x3c, 0x2d, 0x31, 0xba, 0xe9, 0xdf, 0x1e, 0x12, 0xb4,
	0x80, 0xf7, 0x4b, 0x66, 0x9d, 0x61, 0xeb, 0xca, 0x31, 0x25, 0xff, 0x1b, 0xbd, 0xe7, 0x8d, 0xe2,
	0x4b, 0xe6, 0xdf, 0xf9, 0x9f, 0x4f, 0x7e, 0x7d, 0x79, 0x08, 0x3e, 0xfd, 0xfc, 0xfa, 0x78, 0x1c,
	0xae, 0xd9, 0x5c, 0xde, 0x33, 0x6c, 0x7f, 0xf9, 0xe4, 0xdb, 0x21, 0x01, 0xfb, 0x43, 0x02, 0x7e,
	0x1c, 0x12, 0xf0, 0xf9, 0x98, 0xb4, 0xf6, 0xc7, 0xa4, 0xf5, 0xfd, 0x98, 0xb4, 0xde, 0x45, 0xd7,
	0x88, 0xdc, 0x4e, 0x53, 0xbb, 0xee, 0xfa, 0x1b, 0x3e, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x00,
	0x48, 0x0b, 0xaa, 0x25, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxTaxRate != that1.TxTaxRate {
		return false
	}
	if this.InitialRewardPerBlockLumn != that1.InitialRewardPerBlockLumn {
		return false
	}
	if this.HalvingIntervalBlocks != that1.HalvingIntervalBlocks {
		return false
	}
	if this.SupplyCapLumn != that1.SupplyCapLumn {
		return false
	}
	if this.Decimals != that1.Decimals {
		return false
	}
	if this.MinSendUlmn != that1.MinSendUlmn {
		return false
	}
	if this.Denom != that1.Denom {
		return false
	}
	if this.DistributionIntervalBlocks != that1.DistributionIntervalBlocks {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DistributionIntervalBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DistributionIntervalBlocks))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MinSendUlmn != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinSendUlmn))
		i--
		dAtA[i] = 0x30
	}
	if m.Decimals != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x28
	}
	if m.SupplyCapLumn != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SupplyCapLumn))
		i--
		dAtA[i] = 0x20
	}
	if m.HalvingIntervalBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HalvingIntervalBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.InitialRewardPerBlockLumn != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.InitialRewardPerBlockLumn))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxTaxRate) > 0 {
		i -= len(m.TxTaxRate)
		copy(dAtA[i:], m.TxTaxRate)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TxTaxRate)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxTaxRate)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.InitialRewardPerBlockLumn != 0 {
		n += 1 + sovParams(uint64(m.InitialRewardPerBlockLumn))
	}
	if m.HalvingIntervalBlocks != 0 {
		n += 1 + sovParams(uint64(m.HalvingIntervalBlocks))
	}
	if m.SupplyCapLumn != 0 {
		n += 1 + sovParams(uint64(m.SupplyCapLumn))
	}
	if m.Decimals != 0 {
		n += 1 + sovParams(uint64(m.Decimals))
	}
	if m.MinSendUlmn != 0 {
		n += 1 + sovParams(uint64(m.MinSendUlmn))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.DistributionIntervalBlocks != 0 {
		n += 1 + sovParams(uint64(m.DistributionIntervalBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxTaxRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxTaxRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialRewardPerBlockLumn", wireType)
			}
			m.InitialRewardPerBlockLumn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialRewardPerBlockLumn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HalvingIntervalBlocks", wireType)
			}
			m.HalvingIntervalBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HalvingIntervalBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyCapLumn", wireType)
			}
			m.SupplyCapLumn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SupplyCapLumn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSendUlmn", wireType)
			}
			m.MinSendUlmn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinSendUlmn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionIntervalBlocks", wireType)
			}
			m.DistributionIntervalBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionIntervalBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
