// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumen/gateway/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	PlatformCommissionBps        uint32 `protobuf:"varint,1,opt,name=platform_commission_bps,json=platformCommissionBps,proto3" json:"platform_commission_bps,omitempty"`
	MonthSeconds                 uint64 `protobuf:"varint,2,opt,name=month_seconds,json=monthSeconds,proto3" json:"month_seconds,omitempty"`
	FinalizeDelayMonths          uint32 `protobuf:"varint,3,opt,name=finalize_delay_months,json=finalizeDelayMonths,proto3" json:"finalize_delay_months,omitempty"`
	FinalizerRewardBps           uint32 `protobuf:"varint,4,opt,name=finalizer_reward_bps,json=finalizerRewardBps,proto3" json:"finalizer_reward_bps,omitempty"`
	MinPriceUlmnPerMonth         uint64 `protobuf:"varint,5,opt,name=min_price_ulmn_per_month,json=minPriceUlmnPerMonth,proto3" json:"min_price_ulmn_per_month,omitempty"`
	MaxActiveContractsPerGateway uint32 `protobuf:"varint,6,opt,name=max_active_contracts_per_gateway,json=maxActiveContractsPerGateway,proto3" json:"max_active_contracts_per_gateway,omitempty"`
	ActionFeeUlmn                uint64 `protobuf:"varint,7,opt,name=action_fee_ulmn,json=actionFeeUlmn,proto3" json:"action_fee_ulmn,omitempty"`
	RegisterGatewayFeeUlmn       uint64 `protobuf:"varint,8,opt,name=register_gateway_fee_ulmn,json=registerGatewayFeeUlmn,proto3" json:"register_gateway_fee_ulmn,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f12ee76b2aefcba9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPlatformCommissionBps() uint32 {
	if m != nil {
		return m.PlatformCommissionBps
	}
	return 0
}

func (m *Params) GetMonthSeconds() uint64 {
	if m != nil {
		return m.MonthSeconds
	}
	return 0
}

func (m *Params) GetFinalizeDelayMonths() uint32 {
	if m != nil {
		return m.FinalizeDelayMonths
	}
	return 0
}

func (m *Params) GetFinalizerRewardBps() uint32 {
	if m != nil {
		return m.FinalizerRewardBps
	}
	return 0
}

func (m *Params) GetMinPriceUlmnPerMonth() uint64 {
	if m != nil {
		return m.MinPriceUlmnPerMonth
	}
	return 0
}

func (m *Params) GetMaxActiveContractsPerGateway() uint32 {
	if m != nil {
		return m.MaxActiveContractsPerGateway
	}
	return 0
}

func (m *Params) GetActionFeeUlmn() uint64 {
	if m != nil {
		return m.ActionFeeUlmn
	}
	return 0
}

func (m *Params) GetRegisterGatewayFeeUlmn() uint64 {
	if m != nil {
		return m.RegisterGatewayFeeUlmn
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "lumen.gateway.v1.Params")
}

func init() { proto.RegisterFile("lumen/gateway/v1/params.proto", fileDescriptor_f12ee76b2aefcba9) }

var fileDescriptor_f12ee76b2aefcba9 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0xc7, 0x1b, 0xef, 0xb5, 0xca, 0x60, 0x51, 0xc7, 0xde, 0x7b, 0x63, 0xd1, 0x18, 0x14, 0xa4,
	0xb8, 0x68, 0x5a, 0x85, 0x82, 0xee, 0x6c, 0xa5, 0xae, 0x84, 0x50, 0x71, 0xe3, 0x66, 0x98, 0xa6,
	0xd3, 0x38, 0x90, 0xf9, 0x60, 0x66, 0xfa, 0xe5, 0x23, 0xb8, 0xf2, 0x11, 0x7c, 0x04, 0x1f, 0xc3,
	0x65, 0x97, 0x2e, 0xa5, 0x5d, 0xe8, 0x63, 0x48, 0xce, 0x24, 0xed, 0xe2, 0x6e, 0xca, 0x70, 0x7e,
	0xff, 0x8f, 0x43, 0x73, 0xd0, 0xe3, 0x62, 0x29, 0x98, 0x4c, 0x72, 0xea, 0xd8, 0x9a, 0x6e, 0x93,
	0xd5, 0x20, 0xd1, 0xd4, 0x50, 0x61, 0x7b, 0xda, 0x28, 0xa7, 0xf0, 0x3d, 0xc0, 0xbd, 0x0a, 0xf7,
	0x56, 0x83, 0xce, 0x7d, 0x2a, 0xb8, 0x54, 0x09, 0xfc, 0x7a, 0x51, 0xa7, 0x9d, 0xab, 0x5c, 0xc1,
	0x33, 0x29, 0x5f, 0x7e, 0xfa, 0x74, 0x77, 0x86, 0x9a, 0x29, 0x64, 0xe1, 0x21, 0xba, 0xd2, 0x05,
	0x75, 0x0b, 0x65, 0x04, 0xc9, 0x94, 0x10, 0xdc, 0x5a, 0xae, 0x24, 0x99, 0x69, 0x1b, 0x06, 0x71,
	0xd0, 0x6d, 0x4d, 0x2f, 0x6a, 0x3c, 0x3e, 0xd2, 0x91, 0xb6, 0xf8, 0x19, 0x6a, 0x09, 0x25, 0xdd,
	0x17, 0x62, 0x59, 0xa6, 0xe4, 0xdc, 0x86, 0x37, 0xe2, 0xa0, 0x7b, 0x3e, 0xbd, 0x03, 0xc3, 0x8f,
	0x7e, 0x86, 0x5f, 0xa2, 0x8b, 0x05, 0x97, 0xb4, 0xe0, 0x5f, 0x19, 0x99, 0xb3, 0x82, 0x6e, 0x09,
	0x60, 0x1b, 0x9e, 0x41, 0xf4, 0x83, 0x1a, 0xbe, 0x2b, 0xd9, 0x07, 0x40, 0xb8, 0x8f, 0xda, 0xf5,
	0xd8, 0x10, 0xc3, 0xd6, 0xd4, 0xcc, 0x61, 0x9b, 0x73, 0xb0, 0xe0, 0x23, 0x9b, 0x02, 0x2a, 0x57,
	0x19, 0xa2, 0x50, 0x70, 0x49, 0xb4, 0xe1, 0x19, 0x23, 0xcb, 0x42, 0x48, 0xa2, 0x99, 0xf1, 0x4d,
	0xe1, 0x4d, 0xd8, 0xaa, 0x2d, 0xb8, 0x4c, 0x4b, 0xfc, 0xa9, 0x10, 0x32, 0x65, 0x06, 0xaa, 0xf0,
	0x04, 0xc5, 0x82, 0x6e, 0x08, 0xcd, 0x1c, 0x5f, 0x31, 0x92, 0x29, 0xe9, 0x0c, 0xcd, 0x9c, 0x05,
	0x77, 0xf5, 0xaf, 0x86, 0x4d, 0x68, 0x7d, 0x24, 0xe8, 0xe6, 0x2d, 0xc8, 0xc6, 0xb5, 0x2a, 0x65,
	0xe6, 0xbd, 0xd7, 0xe0, 0xe7, 0xe8, 0x6e, 0x99, 0xa1, 0x24, 0x59, 0x30, 0xbf, 0x40, 0x78, 0x0b,
	0x6a, 0x5b, 0x7e, 0x3c, 0x61, 0xd0, 0x8b, 0x5f, 0xa3, 0x87, 0x86, 0xe5, 0xdc, 0xba, 0x53, 0xfe,
	0xc9, 0x71, 0x1b, 0x1c, 0x97, 0xb5, 0xa0, 0xca, 0xae, 0xac, 0x6f, 0xe2, 0x7f, 0x3f, 0x9e, 0x04,
	0xdf, 0xfe, 0xfe, 0x7c, 0x71, 0xe5, 0x6f, 0x62, 0x53, 0x5f, 0x85, 0x4d, 0xfc, 0x77, 0x1c, 0xf5,
	0x7f, 0xed, 0xa3, 0x60, 0xb7, 0x8f, 0x82, 0x3f, 0xfb, 0x28, 0xf8, 0x7e, 0x88, 0x1a, 0xbb, 0x43,
	0xd4, 0xf8, 0x7d, 0x88, 0x1a, 0x9f, 0x2f, 0xaf, 0x59, 0xdc, 0x56, 0x33, 0x3b, 0x6b, 0xc2, 0x2d,
	0xbc, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x28, 0x37, 0x36, 0x4d, 0x67, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PlatformCommissionBps != that1.PlatformCommissionBps {
		return false
	}
	if this.MonthSeconds != that1.MonthSeconds {
		return false
	}
	if this.FinalizeDelayMonths != that1.FinalizeDelayMonths {
		return false
	}
	if this.FinalizerRewardBps != that1.FinalizerRewardBps {
		return false
	}
	if this.MinPriceUlmnPerMonth != that1.MinPriceUlmnPerMonth {
		return false
	}
	if this.MaxActiveContractsPerGateway != that1.MaxActiveContractsPerGateway {
		return false
	}
	if this.ActionFeeUlmn != that1.ActionFeeUlmn {
		return false
	}
	if this.RegisterGatewayFeeUlmn != that1.RegisterGatewayFeeUlmn {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegisterGatewayFeeUlmn != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RegisterGatewayFeeUlmn))
		i--
		dAtA[i] = 0x40
	}
	if m.ActionFeeUlmn != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFeeUlmn))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxActiveContractsPerGateway != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxActiveContractsPerGateway))
		i--
		dAtA[i] = 0x30
	}
	if m.MinPriceUlmnPerMonth != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinPriceUlmnPerMonth))
		i--
		dAtA[i] = 0x28
	}
	if m.FinalizerRewardBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FinalizerRewardBps))
		i--
		dAtA[i] = 0x20
	}
	if m.FinalizeDelayMonths != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FinalizeDelayMonths))
		i--
		dAtA[i] = 0x18
	}
	if m.MonthSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MonthSeconds))
		i--
		dAtA[i] = 0x10
	}
	if m.PlatformCommissionBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PlatformCommissionBps))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PlatformCommissionBps != 0 {
		n += 1 + sovParams(uint64(m.PlatformCommissionBps))
	}
	if m.MonthSeconds != 0 {
		n += 1 + sovParams(uint64(m.MonthSeconds))
	}
	if m.FinalizeDelayMonths != 0 {
		n += 1 + sovParams(uint64(m.FinalizeDelayMonths))
	}
	if m.FinalizerRewardBps != 0 {
		n += 1 + sovParams(uint64(m.FinalizerRewardBps))
	}
	if m.MinPriceUlmnPerMonth != 0 {
		n += 1 + sovParams(uint64(m.MinPriceUlmnPerMonth))
	}
	if m.MaxActiveContractsPerGateway != 0 {
		n += 1 + sovParams(uint64(m.MaxActiveContractsPerGateway))
	}
	if m.ActionFeeUlmn != 0 {
		n += 1 + sovParams(uint64(m.ActionFeeUlmn))
	}
	if m.RegisterGatewayFeeUlmn != 0 {
		n += 1 + sovParams(uint64(m.RegisterGatewayFeeUlmn))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformCommissionBps", wireType)
			}
			m.PlatformCommissionBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlatformCommissionBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthSeconds", wireType)
			}
			m.MonthSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonthSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizeDelayMonths", wireType)
			}
			m.FinalizeDelayMonths = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizeDelayMonths |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizerRewardBps", wireType)
			}
			m.FinalizerRewardBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizerRewardBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPriceUlmnPerMonth", wireType)
			}
			m.MinPriceUlmnPerMonth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinPriceUlmnPerMonth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActiveContractsPerGateway", wireType)
			}
			m.MaxActiveContractsPerGateway = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxActiveContractsPerGateway |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFeeUlmn", wireType)
			}
			m.ActionFeeUlmn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFeeUlmn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterGatewayFeeUlmn", wireType)
			}
			m.RegisterGatewayFeeUlmn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisterGatewayFeeUlmn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
