// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumen/gateway/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/gogoproto/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterGateway struct {
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Payout   string `protobuf:"bytes,2,opt,name=payout,proto3" json:"payout,omitempty"`
	Metadata string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *MsgRegisterGateway) Reset()         { *m = MsgRegisterGateway{} }
func (m *MsgRegisterGateway) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterGateway) ProtoMessage()    {}
func (*MsgRegisterGateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{0}
}
func (m *MsgRegisterGateway) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterGateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterGateway.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterGateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterGateway.Merge(m, src)
}
func (m *MsgRegisterGateway) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterGateway) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterGateway.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterGateway proto.InternalMessageInfo

func (m *MsgRegisterGateway) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgRegisterGateway) GetPayout() string {
	if m != nil {
		return m.Payout
	}
	return ""
}

func (m *MsgRegisterGateway) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type MsgRegisterGatewayResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgRegisterGatewayResponse) Reset()         { *m = MsgRegisterGatewayResponse{} }
func (m *MsgRegisterGatewayResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterGatewayResponse) ProtoMessage()    {}
func (*MsgRegisterGatewayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{1}
}
func (m *MsgRegisterGatewayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterGatewayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterGatewayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterGatewayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterGatewayResponse.Merge(m, src)
}
func (m *MsgRegisterGatewayResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterGatewayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterGatewayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterGatewayResponse proto.InternalMessageInfo

func (m *MsgRegisterGatewayResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateGateway struct {
	Operator  string             `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	GatewayId uint64             `protobuf:"varint,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Payout    *types.StringValue `protobuf:"bytes,3,opt,name=payout,proto3" json:"payout,omitempty"`
	Metadata  *types.StringValue `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Active    *types.BoolValue   `protobuf:"bytes,5,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *MsgUpdateGateway) Reset()         { *m = MsgUpdateGateway{} }
func (m *MsgUpdateGateway) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateGateway) ProtoMessage()    {}
func (*MsgUpdateGateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{2}
}
func (m *MsgUpdateGateway) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateGateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateGateway.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateGateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateGateway.Merge(m, src)
}
func (m *MsgUpdateGateway) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateGateway) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateGateway.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateGateway proto.InternalMessageInfo

func (m *MsgUpdateGateway) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgUpdateGateway) GetGatewayId() uint64 {
	if m != nil {
		return m.GatewayId
	}
	return 0
}

func (m *MsgUpdateGateway) GetPayout() *types.StringValue {
	if m != nil {
		return m.Payout
	}
	return nil
}

func (m *MsgUpdateGateway) GetMetadata() *types.StringValue {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MsgUpdateGateway) GetActive() *types.BoolValue {
	if m != nil {
		return m.Active
	}
	return nil
}

type MsgUpdateGatewayResponse struct {
}

func (m *MsgUpdateGatewayResponse) Reset()         { *m = MsgUpdateGatewayResponse{} }
func (m *MsgUpdateGatewayResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateGatewayResponse) ProtoMessage()    {}
func (*MsgUpdateGatewayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{3}
}
func (m *MsgUpdateGatewayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateGatewayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateGatewayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateGatewayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateGatewayResponse.Merge(m, src)
}
func (m *MsgUpdateGatewayResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateGatewayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateGatewayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateGatewayResponse proto.InternalMessageInfo

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{4}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{5}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgCreateContract struct {
	Client            string `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	GatewayId         uint64 `protobuf:"varint,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	PriceUlmn         uint64 `protobuf:"varint,3,opt,name=price_ulmn,json=priceUlmn,proto3" json:"price_ulmn,omitempty"`
	StorageGbPerMonth uint64 `protobuf:"varint,4,opt,name=storage_gb_per_month,json=storageGbPerMonth,proto3" json:"storage_gb_per_month,omitempty"`
	NetworkGbPerMonth uint64 `protobuf:"varint,5,opt,name=network_gb_per_month,json=networkGbPerMonth,proto3" json:"network_gb_per_month,omitempty"`
	MonthsTotal       uint32 `protobuf:"varint,6,opt,name=months_total,json=monthsTotal,proto3" json:"months_total,omitempty"`
	Metadata          string `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *MsgCreateContract) Reset()         { *m = MsgCreateContract{} }
func (m *MsgCreateContract) String() string { return proto.CompactTextString(m) }
func (*MsgCreateContract) ProtoMessage()    {}
func (*MsgCreateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{6}
}
func (m *MsgCreateContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateContract.Merge(m, src)
}
func (m *MsgCreateContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateContract proto.InternalMessageInfo

func (m *MsgCreateContract) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *MsgCreateContract) GetGatewayId() uint64 {
	if m != nil {
		return m.GatewayId
	}
	return 0
}

func (m *MsgCreateContract) GetPriceUlmn() uint64 {
	if m != nil {
		return m.PriceUlmn
	}
	return 0
}

func (m *MsgCreateContract) GetStorageGbPerMonth() uint64 {
	if m != nil {
		return m.StorageGbPerMonth
	}
	return 0
}

func (m *MsgCreateContract) GetNetworkGbPerMonth() uint64 {
	if m != nil {
		return m.NetworkGbPerMonth
	}
	return 0
}

func (m *MsgCreateContract) GetMonthsTotal() uint32 {
	if m != nil {
		return m.MonthsTotal
	}
	return 0
}

func (m *MsgCreateContract) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type MsgCreateContractResponse struct {
	ContractId uint64 `protobuf:"varint,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
}

func (m *MsgCreateContractResponse) Reset()         { *m = MsgCreateContractResponse{} }
func (m *MsgCreateContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateContractResponse) ProtoMessage()    {}
func (*MsgCreateContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{7}
}
func (m *MsgCreateContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateContractResponse.Merge(m, src)
}
func (m *MsgCreateContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateContractResponse proto.InternalMessageInfo

func (m *MsgCreateContractResponse) GetContractId() uint64 {
	if m != nil {
		return m.ContractId
	}
	return 0
}

type MsgClaimPayment struct {
	Operator   string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	ContractId uint64 `protobuf:"varint,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
}

func (m *MsgClaimPayment) Reset()         { *m = MsgClaimPayment{} }
func (m *MsgClaimPayment) String() string { return proto.CompactTextString(m) }
func (*MsgClaimPayment) ProtoMessage()    {}
func (*MsgClaimPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{8}
}
func (m *MsgClaimPayment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimPayment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimPayment.Merge(m, src)
}
func (m *MsgClaimPayment) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimPayment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimPayment proto.InternalMessageInfo

func (m *MsgClaimPayment) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgClaimPayment) GetContractId() uint64 {
	if m != nil {
		return m.ContractId
	}
	return 0
}

type MsgClaimPaymentResponse struct {
	PaidUlmn string `protobuf:"bytes,1,opt,name=paid_ulmn,json=paidUlmn,proto3" json:"paid_ulmn,omitempty"`
}

func (m *MsgClaimPaymentResponse) Reset()         { *m = MsgClaimPaymentResponse{} }
func (m *MsgClaimPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimPaymentResponse) ProtoMessage()    {}
func (*MsgClaimPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{9}
}
func (m *MsgClaimPaymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimPaymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimPaymentResponse.Merge(m, src)
}
func (m *MsgClaimPaymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimPaymentResponse proto.InternalMessageInfo

func (m *MsgClaimPaymentResponse) GetPaidUlmn() string {
	if m != nil {
		return m.PaidUlmn
	}
	return ""
}

type MsgCancelContract struct {
	Client     string `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	ContractId uint64 `protobuf:"varint,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
}

func (m *MsgCancelContract) Reset()         { *m = MsgCancelContract{} }
func (m *MsgCancelContract) String() string { return proto.CompactTextString(m) }
func (*MsgCancelContract) ProtoMessage()    {}
func (*MsgCancelContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{10}
}
func (m *MsgCancelContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelContract.Merge(m, src)
}
func (m *MsgCancelContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelContract proto.InternalMessageInfo

func (m *MsgCancelContract) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *MsgCancelContract) GetContractId() uint64 {
	if m != nil {
		return m.ContractId
	}
	return 0
}

type MsgCancelContractResponse struct {
	RefundedUlmn string `protobuf:"bytes,1,opt,name=refunded_ulmn,json=refundedUlmn,proto3" json:"refunded_ulmn,omitempty"`
}

func (m *MsgCancelContractResponse) Reset()         { *m = MsgCancelContractResponse{} }
func (m *MsgCancelContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelContractResponse) ProtoMessage()    {}
func (*MsgCancelContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{11}
}
func (m *MsgCancelContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelContractResponse.Merge(m, src)
}
func (m *MsgCancelContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelContractResponse proto.InternalMessageInfo

func (m *MsgCancelContractResponse) GetRefundedUlmn() string {
	if m != nil {
		return m.RefundedUlmn
	}
	return ""
}

type MsgFinalizeContract struct {
	Finalizer  string `protobuf:"bytes,1,opt,name=finalizer,proto3" json:"finalizer,omitempty"`
	ContractId uint64 `protobuf:"varint,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
}

func (m *MsgFinalizeContract) Reset()         { *m = MsgFinalizeContract{} }
func (m *MsgFinalizeContract) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeContract) ProtoMessage()    {}
func (*MsgFinalizeContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{12}
}
func (m *MsgFinalizeContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinalizeContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinalizeContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinalizeContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeContract.Merge(m, src)
}
func (m *MsgFinalizeContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinalizeContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeContract proto.InternalMessageInfo

func (m *MsgFinalizeContract) GetFinalizer() string {
	if m != nil {
		return m.Finalizer
	}
	return ""
}

func (m *MsgFinalizeContract) GetContractId() uint64 {
	if m != nil {
		return m.ContractId
	}
	return 0
}

type MsgFinalizeContractResponse struct {
	RewardUlmn string `protobuf:"bytes,1,opt,name=reward_ulmn,json=rewardUlmn,proto3" json:"reward_ulmn,omitempty"`
}

func (m *MsgFinalizeContractResponse) Reset()         { *m = MsgFinalizeContractResponse{} }
func (m *MsgFinalizeContractResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeContractResponse) ProtoMessage()    {}
func (*MsgFinalizeContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_586f618667a3f0d9, []int{13}
}
func (m *MsgFinalizeContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinalizeContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinalizeContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinalizeContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeContractResponse.Merge(m, src)
}
func (m *MsgFinalizeContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinalizeContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeContractResponse proto.InternalMessageInfo

func (m *MsgFinalizeContractResponse) GetRewardUlmn() string {
	if m != nil {
		return m.RewardUlmn
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgRegisterGateway)(nil), "lumen.gateway.v1.MsgRegisterGateway")
	proto.RegisterType((*MsgRegisterGatewayResponse)(nil), "lumen.gateway.v1.MsgRegisterGatewayResponse")
	proto.RegisterType((*MsgUpdateGateway)(nil), "lumen.gateway.v1.MsgUpdateGateway")
	proto.RegisterType((*MsgUpdateGatewayResponse)(nil), "lumen.gateway.v1.MsgUpdateGatewayResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "lumen.gateway.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "lumen.gateway.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateContract)(nil), "lumen.gateway.v1.MsgCreateContract")
	proto.RegisterType((*MsgCreateContractResponse)(nil), "lumen.gateway.v1.MsgCreateContractResponse")
	proto.RegisterType((*MsgClaimPayment)(nil), "lumen.gateway.v1.MsgClaimPayment")
	proto.RegisterType((*MsgClaimPaymentResponse)(nil), "lumen.gateway.v1.MsgClaimPaymentResponse")
	proto.RegisterType((*MsgCancelContract)(nil), "lumen.gateway.v1.MsgCancelContract")
	proto.RegisterType((*MsgCancelContractResponse)(nil), "lumen.gateway.v1.MsgCancelContractResponse")
	proto.RegisterType((*MsgFinalizeContract)(nil), "lumen.gateway.v1.MsgFinalizeContract")
	proto.RegisterType((*MsgFinalizeContractResponse)(nil), "lumen.gateway.v1.MsgFinalizeContractResponse")
}

func init() { proto.RegisterFile("lumen/gateway/v1/tx.proto", fileDescriptor_586f618667a3f0d9) }

var fileDescriptor_586f618667a3f0d9 = []byte{
	// 926 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x6f, 0xdc, 0x44,
	0x14, 0x8e, 0xb7, 0x9b, 0xd0, 0x7d, 0x9b, 0xa4, 0x89, 0x89, 0xe8, 0xc6, 0x6d, 0xb6, 0xa9, 0x0b,
	0x52, 0x09, 0xed, 0xba, 0x4d, 0xab, 0x08, 0x15, 0x84, 0x20, 0x91, 0xa8, 0x7a, 0x58, 0x29, 0x32,
	0x94, 0x03, 0xaa, 0x64, 0xcd, 0xae, 0x27, 0x8e, 0x85, 0xed, 0xb1, 0x66, 0x66, 0xb3, 0x5d, 0x0e,
	0x08, 0x71, 0xe4, 0xc4, 0x99, 0x7f, 0x00, 0x8e, 0x41, 0xe2, 0xc6, 0x8d, 0x53, 0x8f, 0x15, 0x27,
	0x4e, 0x08, 0x25, 0x87, 0xfc, 0x1b, 0x68, 0xc6, 0xe3, 0xc9, 0xda, 0xbb, 0xc1, 0xab, 0xe6, 0x12,
	0x65, 0xde, 0xfb, 0xbe, 0x79, 0xdf, 0xfb, 0xe5, 0x59, 0x58, 0x8f, 0x06, 0x31, 0x4e, 0x9c, 0x00,
	0x71, 0x3c, 0x44, 0x23, 0xe7, 0xe8, 0xa1, 0xc3, 0x5f, 0x76, 0x52, 0x4a, 0x38, 0x31, 0x57, 0xa4,
	0xab, 0xa3, 0x5c, 0x9d, 0xa3, 0x87, 0xd6, 0x2a, 0x8a, 0xc3, 0x84, 0x38, 0xf2, 0x6f, 0x06, 0xb2,
	0xae, 0xf7, 0x09, 0x8b, 0x09, 0x73, 0x62, 0x16, 0x08, 0x72, 0xcc, 0x02, 0xe5, 0x58, 0xcf, 0x1c,
	0x9e, 0x3c, 0x39, 0xd9, 0x41, 0xb9, 0xd6, 0x02, 0x12, 0x90, 0xcc, 0x2e, 0xfe, 0x53, 0xd6, 0x76,
	0x40, 0x48, 0x10, 0x61, 0x47, 0x9e, 0x7a, 0x83, 0x03, 0x67, 0x48, 0x51, 0x9a, 0x62, 0x9a, 0xb3,
	0x6e, 0x4e, 0x2a, 0x1d, 0xa5, 0x38, 0xf7, 0x6e, 0x4c, 0x78, 0x53, 0x44, 0x51, 0xac, 0xdc, 0xf6,
	0x2f, 0x06, 0x98, 0x5d, 0x16, 0xb8, 0x38, 0x08, 0x19, 0xc7, 0xf4, 0x69, 0x06, 0x33, 0x1f, 0xc3,
	0x55, 0x92, 0x62, 0x8a, 0x38, 0xa1, 0x2d, 0x63, 0xd3, 0xb8, 0xdb, 0xd8, 0x6d, 0xfd, 0xf5, 0xfb,
	0xfd, 0x35, 0xa5, 0xf6, 0x33, 0xdf, 0xa7, 0x98, 0xb1, 0x2f, 0x38, 0x0d, 0x93, 0xc0, 0xd5, 0x48,
	0xf3, 0x01, 0x2c, 0xa4, 0x68, 0x44, 0x06, 0xbc, 0x55, 0xab, 0xe0, 0x28, 0x9c, 0x69, 0xc1, 0xd5,
	0x18, 0x73, 0xe4, 0x23, 0x8e, 0x5a, 0x57, 0x04, 0xc7, 0xd5, 0xe7, 0x27, 0x4b, 0x3f, 0x9c, 0x1d,
	0x6f, 0xe9, 0xcb, 0xed, 0x7b, 0x60, 0x4d, 0x0a, 0x75, 0x31, 0x4b, 0x49, 0xc2, 0xb0, 0xb9, 0x0c,
	0xb5, 0xd0, 0x97, 0x52, 0xeb, 0x6e, 0x2d, 0xf4, 0xed, 0x9f, 0x6b, 0xb0, 0xd2, 0x65, 0xc1, 0xf3,
	0xd4, 0x47, 0x1c, 0x5f, 0x2e, 0xab, 0x0d, 0x00, 0x55, 0x3d, 0x2f, 0xf4, 0x65, 0x66, 0x75, 0xb7,
	0xa1, 0x2c, 0xcf, 0x7c, 0xf3, 0xb1, 0x4e, 0x5a, 0x24, 0xd0, 0xdc, 0xbe, 0xd9, 0xc9, 0xfa, 0xd5,
	0xc9, 0xfb, 0xd5, 0xc9, 0x6e, 0xfc, 0x0a, 0x45, 0x03, 0xac, 0x13, 0xff, 0x70, 0x2c, 0xf1, 0xfa,
	0x0c, 0x3c, 0x8d, 0x36, 0xb7, 0x61, 0x01, 0xf5, 0x79, 0x78, 0x84, 0x5b, 0xf3, 0x92, 0x67, 0x4d,
	0xf0, 0x76, 0x09, 0x89, 0x54, 0xb4, 0x0c, 0x59, 0x2e, 0xa5, 0x05, 0xad, 0x72, 0x6d, 0xf2, 0x42,
	0xda, 0x7f, 0x18, 0x70, 0x4d, 0x3b, 0xf7, 0xe5, 0xa8, 0x98, 0x3b, 0xd0, 0x40, 0x03, 0x7e, 0x48,
	0x68, 0xc8, 0x47, 0x95, 0x85, 0x3b, 0x87, 0x9a, 0x1f, 0x89, 0xd2, 0x88, 0x1b, 0x64, 0xd5, 0x9a,
	0xdb, 0xad, 0x4e, 0x79, 0x73, 0x3a, 0x59, 0x84, 0xdd, 0xc6, 0xab, 0x7f, 0x6e, 0xcd, 0xfd, 0x7a,
	0x76, 0xbc, 0x65, 0xb8, 0x8a, 0xf2, 0xe4, 0x91, 0xd0, 0x7c, 0x7e, 0xd9, 0x8f, 0x67, 0xc7, 0x5b,
	0x9b, 0xd9, 0x2c, 0xbf, 0xcc, 0xa7, 0x99, 0x39, 0x25, 0xa5, 0xf6, 0x3a, 0x5c, 0x2f, 0x99, 0x74,
	0x62, 0xbf, 0xd5, 0x60, 0xb5, 0xcb, 0x82, 0x3d, 0x8a, 0x11, 0xc7, 0x7b, 0x24, 0xe1, 0x14, 0xf5,
	0xb9, 0x18, 0xd9, 0x7e, 0x14, 0xe2, 0x84, 0x57, 0xe6, 0xa5, 0x70, 0x55, 0xe3, 0xb0, 0x01, 0x90,
	0xd2, 0xb0, 0x8f, 0xbd, 0x41, 0x14, 0x27, 0x72, 0x24, 0xea, 0x6e, 0x43, 0x5a, 0x9e, 0x47, 0x71,
	0x62, 0x3a, 0xb0, 0xc6, 0x38, 0xa1, 0x28, 0xc0, 0x5e, 0xd0, 0xf3, 0x52, 0x4c, 0xbd, 0x98, 0x24,
	0xfc, 0x50, 0xce, 0x40, 0xdd, 0x5d, 0x55, 0xbe, 0xa7, 0xbd, 0x7d, 0x4c, 0xbb, 0xc2, 0x21, 0x08,
	0x09, 0xe6, 0x43, 0x42, 0xbf, 0x29, 0x12, 0xe6, 0x33, 0x82, 0xf2, 0x8d, 0x11, 0x6e, 0xc3, 0xa2,
	0x44, 0x30, 0x8f, 0x13, 0x8e, 0xa2, 0xd6, 0xc2, 0xa6, 0x71, 0x77, 0xc9, 0x6d, 0x66, 0xb6, 0x2f,
	0x85, 0xa9, 0xb0, 0x75, 0x6f, 0x95, 0xb6, 0xae, 0x29, 0xca, 0xae, 0x72, 0xb5, 0x3f, 0x86, 0xf5,
	0x89, 0x92, 0xe9, 0x95, 0xbb, 0x05, 0xcd, 0xbe, 0xb2, 0x79, 0x7a, 0xf7, 0x20, 0x37, 0x3d, 0xf3,
	0xed, 0xa1, 0x9c, 0xa4, 0xbd, 0x08, 0x85, 0xf1, 0x3e, 0x1a, 0xc5, 0xa2, 0x78, 0x6f, 0xb6, 0x81,
	0xa5, 0x48, 0xb5, 0x72, 0xa4, 0xf2, 0x7c, 0xef, 0xc8, 0x29, 0x18, 0x0f, 0xac, 0x45, 0xdf, 0x80,
	0x46, 0x8a, 0x42, 0x3f, 0xeb, 0x8e, 0x91, 0xe5, 0x2e, 0x0c, 0xa2, 0x39, 0x36, 0xcb, 0x26, 0x04,
	0x25, 0x7d, 0x1c, 0x5d, 0x62, 0x42, 0x2a, 0xe5, 0x16, 0x6a, 0xfc, 0x69, 0x56, 0xe3, 0x42, 0x50,
	0x2d, 0xf7, 0x0e, 0x2c, 0x51, 0x7c, 0x30, 0x48, 0x7c, 0x5c, 0x90, 0xbc, 0x98, 0x1b, 0xa5, 0xec,
	0xef, 0xe0, 0xed, 0x2e, 0x0b, 0x3e, 0x0f, 0x13, 0x14, 0x85, 0xdf, 0x9e, 0x8f, 0xf6, 0x0e, 0x34,
	0x0e, 0x94, 0xad, 0xba, 0xd8, 0xe7, 0xd0, 0x6a, 0xf9, 0xcb, 0x72, 0x33, 0x35, 0xc1, 0xfe, 0x04,
	0x6e, 0x4c, 0x89, 0x3f, 0x3e, 0x27, 0x14, 0x0f, 0x11, 0x2d, 0x64, 0x00, 0x99, 0x49, 0xe8, 0xdf,
	0xfe, 0x73, 0x1e, 0xae, 0x74, 0x59, 0x60, 0xbe, 0x80, 0xc5, 0xc2, 0x67, 0xe7, 0xf6, 0xe4, 0xe7,
	0xa2, 0xb4, 0xdc, 0xd6, 0xfb, 0x95, 0x10, 0x2d, 0x03, 0xc3, 0xb5, 0xf2, 0x2b, 0xf7, 0xee, 0x54,
	0x76, 0x09, 0x65, 0xdd, 0x9b, 0x05, 0xa5, 0xc3, 0x78, 0xb0, 0x54, 0x7c, 0x74, 0xec, 0xff, 0x91,
	0x98, 0x87, 0xd8, 0xaa, 0xc6, 0xe8, 0x00, 0x3d, 0x58, 0x2e, 0x7d, 0xc3, 0xee, 0x4c, 0x65, 0x17,
	0x41, 0xd6, 0x07, 0x33, 0x80, 0x74, 0x8c, 0x17, 0xb0, 0x58, 0x58, 0xdb, 0xe9, 0x9d, 0x18, 0x87,
	0x5c, 0xd0, 0x89, 0xa9, 0x3b, 0x28, 0x32, 0x28, 0xee, 0xd8, 0x05, 0x19, 0x14, 0x40, 0x17, 0x65,
	0x30, 0x7d, 0x71, 0x0e, 0x61, 0x65, 0x62, 0x21, 0xde, 0x9b, 0x7a, 0x41, 0x19, 0x66, 0xdd, 0x9f,
	0x09, 0x96, 0x47, 0xb2, 0xe6, 0xbf, 0x17, 0xcf, 0xd6, 0xee, 0x83, 0x57, 0x27, 0x6d, 0xe3, 0xf5,
	0x49, 0xdb, 0xf8, 0xf7, 0xa4, 0x6d, 0xfc, 0x74, 0xda, 0x9e, 0x7b, 0x7d, 0xda, 0x9e, 0xfb, 0xfb,
	0xb4, 0x3d, 0xf7, 0xf5, 0x3b, 0x13, 0xaf, 0x96, 0xfc, 0x7d, 0xd6, 0x5b, 0x90, 0x0f, 0xf6, 0xa3,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xa7, 0x96, 0x3e, 0x6a, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	RegisterGateway(ctx context.Context, in *MsgRegisterGateway, opts ...grpc.CallOption) (*MsgRegisterGatewayResponse, error)
	UpdateGateway(ctx context.Context, in *MsgUpdateGateway, opts ...grpc.CallOption) (*MsgUpdateGatewayResponse, error)
	CreateContract(ctx context.Context, in *MsgCreateContract, opts ...grpc.CallOption) (*MsgCreateContractResponse, error)
	ClaimPayment(ctx context.Context, in *MsgClaimPayment, opts ...grpc.CallOption) (*MsgClaimPaymentResponse, error)
	CancelContract(ctx context.Context, in *MsgCancelContract, opts ...grpc.CallOption) (*MsgCancelContractResponse, error)
	FinalizeContract(ctx context.Context, in *MsgFinalizeContract, opts ...grpc.CallOption) (*MsgFinalizeContractResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/lumen.gateway.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterGateway(ctx context.Context, in *MsgRegisterGateway, opts ...grpc.CallOption) (*MsgRegisterGatewayResponse, error) {
	out := new(MsgRegisterGatewayResponse)
	err := c.cc.Invoke(ctx, "/lumen.gateway.v1.Msg/RegisterGateway", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateGateway(ctx context.Context, in *MsgUpdateGateway, opts ...grpc.CallOption) (*MsgUpdateGatewayResponse, error) {
	out := new(MsgUpdateGatewayResponse)
	err := c.cc.Invoke(ctx, "/lumen.gateway.v1.Msg/UpdateGateway", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateContract(ctx context.Context, in *MsgCreateContract, opts ...grpc.CallOption) (*MsgCreateContractResponse, error) {
	out := new(MsgCreateContractResponse)
	err := c.cc.Invoke(ctx, "/lumen.gateway.v1.Msg/CreateContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimPayment(ctx context.Context, in *MsgClaimPayment, opts ...grpc.CallOption) (*MsgClaimPaymentResponse, error) {
	out := new(MsgClaimPaymentResponse)
	err := c.cc.Invoke(ctx, "/lumen.gateway.v1.Msg/ClaimPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelContract(ctx context.Context, in *MsgCancelContract, opts ...grpc.CallOption) (*MsgCancelContractResponse, error) {
	out := new(MsgCancelContractResponse)
	err := c.cc.Invoke(ctx, "/lumen.gateway.v1.Msg/CancelContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FinalizeContract(ctx context.Context, in *MsgFinalizeContract, opts ...grpc.CallOption) (*MsgFinalizeContractResponse, error) {
	out := new(MsgFinalizeContractResponse)
	err := c.cc.Invoke(ctx, "/lumen.gateway.v1.Msg/FinalizeContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	RegisterGateway(context.Context, *MsgRegisterGateway) (*MsgRegisterGatewayResponse, error)
	UpdateGateway(context.Context, *MsgUpdateGateway) (*MsgUpdateGatewayResponse, error)
	CreateContract(context.Context, *MsgCreateContract) (*MsgCreateContractResponse, error)
	ClaimPayment(context.Context, *MsgClaimPayment) (*MsgClaimPaymentResponse, error)
	CancelContract(context.Context, *MsgCancelContract) (*MsgCancelContractResponse, error)
	FinalizeContract(context.Context, *MsgFinalizeContract) (*MsgFinalizeContractResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) RegisterGateway(ctx context.Context, req *MsgRegisterGateway) (*MsgRegisterGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGateway not implemented")
}
func (*UnimplementedMsgServer) UpdateGateway(ctx context.Context, req *MsgUpdateGateway) (*MsgUpdateGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGateway not implemented")
}
func (*UnimplementedMsgServer) CreateContract(ctx context.Context, req *MsgCreateContract) (*MsgCreateContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContract not implemented")
}
func (*UnimplementedMsgServer) ClaimPayment(ctx context.Context, req *MsgClaimPayment) (*MsgClaimPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimPayment not implemented")
}
func (*UnimplementedMsgServer) CancelContract(ctx context.Context, req *MsgCancelContract) (*MsgCancelContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelContract not implemented")
}
func (*UnimplementedMsgServer) FinalizeContract(ctx context.Context, req *MsgFinalizeContract) (*MsgFinalizeContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeContract not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.gateway.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterGateway)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.gateway.v1.Msg/RegisterGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterGateway(ctx, req.(*MsgRegisterGateway))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateGateway)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.gateway.v1.Msg/UpdateGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateGateway(ctx, req.(*MsgUpdateGateway))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.gateway.v1.Msg/CreateContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateContract(ctx, req.(*MsgCreateContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimPayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.gateway.v1.Msg/ClaimPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimPayment(ctx, req.(*MsgClaimPayment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.gateway.v1.Msg/CancelContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelContract(ctx, req.(*MsgCancelContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FinalizeContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFinalizeContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FinalizeContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.gateway.v1.Msg/FinalizeContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FinalizeContract(ctx, req.(*MsgFinalizeContract))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lumen.gateway.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterGateway",
			Handler:    _Msg_RegisterGateway_Handler,
		},
		{
			MethodName: "UpdateGateway",
			Handler:    _Msg_UpdateGateway_Handler,
		},
		{
			MethodName: "CreateContract",
			Handler:    _Msg_CreateContract_Handler,
		},
		{
			MethodName: "ClaimPayment",
			Handler:    _Msg_ClaimPayment_Handler,
		},
		{
			MethodName: "CancelContract",
			Handler:    _Msg_CancelContract_Handler,
		},
		{
			MethodName: "FinalizeContract",
			Handler:    _Msg_FinalizeContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lumen/gateway/v1/tx.proto",
}

func (m *MsgRegisterGateway) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterGateway) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterGateway) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Payout) > 0 {
		i -= len(m.Payout)
		copy(dAtA[i:], m.Payout)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payout)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterGatewayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterGatewayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterGatewayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateGateway) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateGateway) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateGateway) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active != nil {
		{
			size, err := m.Active.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Payout != nil {
		{
			size, err := m.Payout.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.GatewayId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GatewayId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateGatewayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateGatewayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateGatewayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MonthsTotal != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MonthsTotal))
		i--
		dAtA[i] = 0x30
	}
	if m.NetworkGbPerMonth != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NetworkGbPerMonth))
		i--
		dAtA[i] = 0x28
	}
	if m.StorageGbPerMonth != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StorageGbPerMonth))
		i--
		dAtA[i] = 0x20
	}
	if m.PriceUlmn != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PriceUlmn))
		i--
		dAtA[i] = 0x18
	}
	if m.GatewayId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GatewayId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Client) > 0 {
		i -= len(m.Client)
		copy(dAtA[i:], m.Client)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Client)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ContractId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ContractId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimPayment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimPayment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimPayment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ContractId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ContractId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimPaymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimPaymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimPaymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PaidUlmn) > 0 {
		i -= len(m.PaidUlmn)
		copy(dAtA[i:], m.PaidUlmn)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PaidUlmn)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ContractId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ContractId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Client) > 0 {
		i -= len(m.Client)
		copy(dAtA[i:], m.Client)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Client)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RefundedUlmn) > 0 {
		i -= len(m.RefundedUlmn)
		copy(dAtA[i:], m.RefundedUlmn)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RefundedUlmn)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFinalizeContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinalizeContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinalizeContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ContractId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ContractId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Finalizer) > 0 {
		i -= len(m.Finalizer)
		copy(dAtA[i:], m.Finalizer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Finalizer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFinalizeContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinalizeContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinalizeContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RewardUlmn) > 0 {
		i -= len(m.RewardUlmn)
		copy(dAtA[i:], m.RewardUlmn)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RewardUlmn)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterGateway) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payout)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterGatewayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateGateway) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.GatewayId != 0 {
		n += 1 + sovTx(uint64(m.GatewayId))
	}
	if m.Payout != nil {
		l = m.Payout.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Active != nil {
		l = m.Active.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateGatewayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Client)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.GatewayId != 0 {
		n += 1 + sovTx(uint64(m.GatewayId))
	}
	if m.PriceUlmn != 0 {
		n += 1 + sovTx(uint64(m.PriceUlmn))
	}
	if m.StorageGbPerMonth != 0 {
		n += 1 + sovTx(uint64(m.StorageGbPerMonth))
	}
	if m.NetworkGbPerMonth != 0 {
		n += 1 + sovTx(uint64(m.NetworkGbPerMonth))
	}
	if m.MonthsTotal != 0 {
		n += 1 + sovTx(uint64(m.MonthsTotal))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ContractId != 0 {
		n += 1 + sovTx(uint64(m.ContractId))
	}
	return n
}

func (m *MsgClaimPayment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ContractId != 0 {
		n += 1 + sovTx(uint64(m.ContractId))
	}
	return n
}

func (m *MsgClaimPaymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PaidUlmn)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Client)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ContractId != 0 {
		n += 1 + sovTx(uint64(m.ContractId))
	}
	return n
}

func (m *MsgCancelContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RefundedUlmn)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgFinalizeContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Finalizer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ContractId != 0 {
		n += 1 + sovTx(uint64(m.ContractId))
	}
	return n
}

func (m *MsgFinalizeContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RewardUlmn)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterGateway) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterGateway: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterGateway: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payout = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterGatewayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterGatewayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterGatewayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateGateway) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateGateway: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateGateway: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayId", wireType)
			}
			m.GatewayId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GatewayId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Payout == nil {
				m.Payout = &types.StringValue{}
			}
			if err := m.Payout.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &types.StringValue{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Active == nil {
				m.Active = &types.BoolValue{}
			}
			if err := m.Active.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateGatewayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateGatewayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateGatewayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Client", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Client = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayId", wireType)
			}
			m.GatewayId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GatewayId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceUlmn", wireType)
			}
			m.PriceUlmn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceUlmn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageGbPerMonth", wireType)
			}
			m.StorageGbPerMonth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageGbPerMonth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkGbPerMonth", wireType)
			}
			m.NetworkGbPerMonth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NetworkGbPerMonth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthsTotal", wireType)
			}
			m.MonthsTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonthsTotal |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
			}
			m.ContractId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimPayment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimPayment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimPayment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
			}
			m.ContractId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimPaymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimPaymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimPaymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaidUlmn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaidUlmn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Client", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Client = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
			}
			m.ContractId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefundedUlmn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefundedUlmn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinalizeContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinalizeContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinalizeContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Finalizer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Finalizer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
			}
			m.ContractId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinalizeContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinalizeContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinalizeContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardUlmn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardUlmn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
