// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumen/release/v1/bundle.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Bundle struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Os            string `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Cid           string `protobuf:"bytes,6,opt,name=cid,proto3" json:"cid,omitempty"`
	Sha_256       string `protobuf:"bytes,7,opt,name=sha_256,json=sha256,proto3" json:"sha_256,omitempty"`
	SizeBytes     uint64 `protobuf:"varint,8,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAtUnix uint64 `protobuf:"varint,9,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Creator       string `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Bundle) Reset()         { *m = Bundle{} }
func (m *Bundle) String() string { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()    {}
func (*Bundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_37fbc3be1b475079, []int{0}
}
func (m *Bundle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Bundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Bundle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Bundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bundle.Merge(m, src)
}
func (m *Bundle) XXX_Size() int {
	return m.Size()
}
func (m *Bundle) XXX_DiscardUnknown() {
	xxx_messageInfo_Bundle.DiscardUnknown(m)
}

var xxx_messageInfo_Bundle proto.InternalMessageInfo

func (m *Bundle) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bundle) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Bundle) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Bundle) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Bundle) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Bundle) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Bundle) GetSha_256() string {
	if m != nil {
		return m.Sha_256
	}
	return ""
}

func (m *Bundle) GetSizeBytes() uint64 {
	if m != nil {
		return m.SizeBytes
	}
	return 0
}

func (m *Bundle) GetCreatedAtUnix() uint64 {
	if m != nil {
		return m.CreatedAtUnix
	}
	return 0
}

func (m *Bundle) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Bundle)(nil), "lumen.release.v1.Bundle")
}

func init() { proto.RegisterFile("lumen/release/v1/bundle.proto", fileDescriptor_37fbc3be1b475079) }

var fileDescriptor_37fbc3be1b475079 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xc1, 0x6a, 0x32, 0x31,
	0x14, 0x85, 0xcd, 0xa8, 0xe3, 0xef, 0x85, 0xbf, 0x95, 0xd0, 0xd2, 0x6c, 0x0c, 0xd2, 0x45, 0x71,
	0xe5, 0xa0, 0x45, 0xf7, 0xf5, 0x11, 0x84, 0x6e, 0xba, 0x19, 0xa2, 0xb9, 0x60, 0xc0, 0x26, 0x92,
	0x44, 0xd1, 0x3e, 0x45, 0x1f, 0xab, 0x4b, 0x97, 0x5d, 0x96, 0x99, 0x97, 0xe8, 0xb2, 0xcc, 0x9d,
	0x69, 0x77, 0xf7, 0x7c, 0xe7, 0x5c, 0x38, 0x1c, 0x18, 0xee, 0x0e, 0xaf, 0x68, 0x33, 0x8f, 0x3b,
	0x54, 0x01, 0xb3, 0xe3, 0x34, 0x5b, 0x1f, 0xac, 0xde, 0xe1, 0x64, 0xef, 0x5d, 0x74, 0x7c, 0x40,
	0xf6, 0xa4, 0xb1, 0x27, 0xc7, 0xe9, 0xfd, 0x37, 0x83, 0x74, 0x49, 0x11, 0x7e, 0x05, 0x89, 0xd1,
	0x82, 0x8d, 0xd8, 0xb8, 0xb3, 0x4a, 0x8c, 0xe6, 0x37, 0xd0, 0x35, 0x56, 0xe3, 0x49, 0x24, 0x23,
	0x36, 0xee, 0xaf, 0x6a, 0xc1, 0x05, 0xf4, 0x8e, 0xe8, 0x83, 0x71, 0x56, 0xb4, 0x89, 0xff, 0xca,
	0xea, 0xdf, 0x05, 0xd1, 0x21, 0x98, 0xb8, 0xc0, 0x39, 0x74, 0x94, 0xdf, 0x6c, 0x45, 0x97, 0x08,
	0xdd, 0x7c, 0x00, 0xed, 0x8d, 0xd1, 0x22, 0x25, 0x54, 0x9d, 0xfc, 0x0e, 0x7a, 0x61, 0xab, 0xf2,
	0xd9, 0x7c, 0x21, 0x7a, 0x44, 0xd3, 0xb0, 0x55, 0xb3, 0xf9, 0x82, 0x0f, 0x01, 0x82, 0x79, 0xc3,
	0x7c, 0x7d, 0x8e, 0x18, 0xc4, 0x3f, 0xaa, 0xd5, 0xaf, 0xc8, 0xb2, 0x02, 0xfc, 0x01, 0xae, 0x37,
	0x1e, 0x55, 0x44, 0x9d, 0xab, 0x98, 0x1f, 0xac, 0x39, 0x89, 0x3e, 0x65, 0xfe, 0x37, 0xf8, 0x29,
	0x3e, 0x5b, 0x43, 0x7d, 0x09, 0x38, 0x2f, 0xa0, 0xee, 0xdb, 0xc8, 0x65, 0xf6, 0x51, 0x48, 0x76,
	0x29, 0x24, 0xfb, 0x2a, 0x24, 0x7b, 0x2f, 0x65, 0xeb, 0x52, 0xca, 0xd6, 0x67, 0x29, 0x5b, 0x2f,
	0xb7, 0xf5, 0x8a, 0xa7, 0xbf, 0x1d, 0xe3, 0x79, 0x8f, 0x61, 0x9d, 0xd2, 0x88, 0x8f, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x1a, 0x30, 0x58, 0x1a, 0x65, 0x01, 0x00, 0x00,
}

func (m *Bundle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Bundle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Bundle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintBundle(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x52
	}
	if m.CreatedAtUnix != 0 {
		i = encodeVarintBundle(dAtA, i, uint64(m.CreatedAtUnix))
		i--
		dAtA[i] = 0x48
	}
	if m.SizeBytes != 0 {
		i = encodeVarintBundle(dAtA, i, uint64(m.SizeBytes))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Sha_256) > 0 {
		i -= len(m.Sha_256)
		copy(dAtA[i:], m.Sha_256)
		i = encodeVarintBundle(dAtA, i, uint64(len(m.Sha_256)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintBundle(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Arch) > 0 {
		i -= len(m.Arch)
		copy(dAtA[i:], m.Arch)
		i = encodeVarintBundle(dAtA, i, uint64(len(m.Arch)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Os) > 0 {
		i -= len(m.Os)
		copy(dAtA[i:], m.Os)
		i = encodeVarintBundle(dAtA, i, uint64(len(m.Os)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintBundle(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintBundle(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintBundle(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBundle(dAtA []byte, offset int, v uint64) int {
	offset -= sovBundle(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Bundle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovBundle(uint64(m.Id))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovBundle(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovBundle(uint64(l))
	}
	l = len(m.Os)
	if l > 0 {
		n += 1 + l + sovBundle(uint64(l))
	}
	l = len(m.Arch)
	if l > 0 {
		n += 1 + l + sovBundle(uint64(l))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovBundle(uint64(l))
	}
	l = len(m.Sha_256)
	if l > 0 {
		n += 1 + l + sovBundle(uint64(l))
	}
	if m.SizeBytes != 0 {
		n += 1 + sovBundle(uint64(m.SizeBytes))
	}
	if m.CreatedAtUnix != 0 {
		n += 1 + sovBundle(uint64(m.CreatedAtUnix))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovBundle(uint64(l))
	}
	return n
}

func sovBundle(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBundle(x uint64) (n int) {
	return sovBundle(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Bundle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBundle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bundle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bundle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBundle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBundle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Os", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBundle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Os = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBundle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBundle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sha_256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBundle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sha_256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SizeBytes", wireType)
			}
			m.SizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SizeBytes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtUnix", wireType)
			}
			m.CreatedAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtUnix |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBundle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBundle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBundle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBundle(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBundle
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBundle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBundle
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBundle
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBundle
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBundle        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBundle          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBundle = fmt.Errorf("proto: unexpected end of group")
)
