// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumen/release/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgPublishRelease struct {
	Creator string  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Release Release `protobuf:"bytes,2,opt,name=release,proto3" json:"release"`
}

func (m *MsgPublishRelease) Reset()         { *m = MsgPublishRelease{} }
func (m *MsgPublishRelease) String() string { return proto.CompactTextString(m) }
func (*MsgPublishRelease) ProtoMessage()    {}
func (*MsgPublishRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{0}
}
func (m *MsgPublishRelease) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPublishRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPublishRelease.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPublishRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPublishRelease.Merge(m, src)
}
func (m *MsgPublishRelease) XXX_Size() int {
	return m.Size()
}
func (m *MsgPublishRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPublishRelease.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPublishRelease proto.InternalMessageInfo

func (m *MsgPublishRelease) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgPublishRelease) GetRelease() Release {
	if m != nil {
		return m.Release
	}
	return Release{}
}

type MsgPublishReleaseResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgPublishReleaseResponse) Reset()         { *m = MsgPublishReleaseResponse{} }
func (m *MsgPublishReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPublishReleaseResponse) ProtoMessage()    {}
func (*MsgPublishReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{1}
}
func (m *MsgPublishReleaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPublishReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPublishReleaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPublishReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPublishReleaseResponse.Merge(m, src)
}
func (m *MsgPublishReleaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPublishReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPublishReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPublishReleaseResponse proto.InternalMessageInfo

func (m *MsgPublishReleaseResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgYankRelease struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgYankRelease) Reset()         { *m = MsgYankRelease{} }
func (m *MsgYankRelease) String() string { return proto.CompactTextString(m) }
func (*MsgYankRelease) ProtoMessage()    {}
func (*MsgYankRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{2}
}
func (m *MsgYankRelease) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgYankRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgYankRelease.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgYankRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgYankRelease.Merge(m, src)
}
func (m *MsgYankRelease) XXX_Size() int {
	return m.Size()
}
func (m *MsgYankRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgYankRelease.DiscardUnknown(m)
}

var xxx_messageInfo_MsgYankRelease proto.InternalMessageInfo

func (m *MsgYankRelease) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgYankRelease) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgYankReleaseResponse struct {
}

func (m *MsgYankReleaseResponse) Reset()         { *m = MsgYankReleaseResponse{} }
func (m *MsgYankReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgYankReleaseResponse) ProtoMessage()    {}
func (*MsgYankReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{3}
}
func (m *MsgYankReleaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgYankReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgYankReleaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgYankReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgYankReleaseResponse.Merge(m, src)
}
func (m *MsgYankReleaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgYankReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgYankReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgYankReleaseResponse proto.InternalMessageInfo

type MsgMirrorRelease struct {
	Creator       string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id            uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ArtifactIndex uint32   `protobuf:"varint,3,opt,name=artifact_index,json=artifactIndex,proto3" json:"artifact_index,omitempty"`
	NewUrls       []string `protobuf:"bytes,4,rep,name=new_urls,json=newUrls,proto3" json:"new_urls,omitempty"`
}

func (m *MsgMirrorRelease) Reset()         { *m = MsgMirrorRelease{} }
func (m *MsgMirrorRelease) String() string { return proto.CompactTextString(m) }
func (*MsgMirrorRelease) ProtoMessage()    {}
func (*MsgMirrorRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{4}
}
func (m *MsgMirrorRelease) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMirrorRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMirrorRelease.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMirrorRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMirrorRelease.Merge(m, src)
}
func (m *MsgMirrorRelease) XXX_Size() int {
	return m.Size()
}
func (m *MsgMirrorRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMirrorRelease.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMirrorRelease proto.InternalMessageInfo

func (m *MsgMirrorRelease) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgMirrorRelease) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgMirrorRelease) GetArtifactIndex() uint32 {
	if m != nil {
		return m.ArtifactIndex
	}
	return 0
}

func (m *MsgMirrorRelease) GetNewUrls() []string {
	if m != nil {
		return m.NewUrls
	}
	return nil
}

type MsgMirrorReleaseResponse struct {
	Added uint32 `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
}

func (m *MsgMirrorReleaseResponse) Reset()         { *m = MsgMirrorReleaseResponse{} }
func (m *MsgMirrorReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMirrorReleaseResponse) ProtoMessage()    {}
func (*MsgMirrorReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{5}
}
func (m *MsgMirrorReleaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMirrorReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMirrorReleaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMirrorReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMirrorReleaseResponse.Merge(m, src)
}
func (m *MsgMirrorReleaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMirrorReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMirrorReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMirrorReleaseResponse proto.InternalMessageInfo

func (m *MsgMirrorReleaseResponse) GetAdded() uint32 {
	if m != nil {
		return m.Added
	}
	return 0
}

type MsgSetEmergency struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id           uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	EmergencyOk  bool   `protobuf:"varint,3,opt,name=emergency_ok,json=emergencyOk,proto3" json:"emergency_ok,omitempty"`
	EmergencyTtl int64  `protobuf:"varint,4,opt,name=emergency_ttl,json=emergencyTtl,proto3" json:"emergency_ttl,omitempty"`
}

func (m *MsgSetEmergency) Reset()         { *m = MsgSetEmergency{} }
func (m *MsgSetEmergency) String() string { return proto.CompactTextString(m) }
func (*MsgSetEmergency) ProtoMessage()    {}
func (*MsgSetEmergency) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{6}
}
func (m *MsgSetEmergency) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetEmergency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetEmergency.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetEmergency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetEmergency.Merge(m, src)
}
func (m *MsgSetEmergency) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetEmergency) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetEmergency.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetEmergency proto.InternalMessageInfo

func (m *MsgSetEmergency) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetEmergency) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgSetEmergency) GetEmergencyOk() bool {
	if m != nil {
		return m.EmergencyOk
	}
	return false
}

func (m *MsgSetEmergency) GetEmergencyTtl() int64 {
	if m != nil {
		return m.EmergencyTtl
	}
	return 0
}

type MsgSetEmergencyResponse struct {
}

func (m *MsgSetEmergencyResponse) Reset()         { *m = MsgSetEmergencyResponse{} }
func (m *MsgSetEmergencyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetEmergencyResponse) ProtoMessage()    {}
func (*MsgSetEmergencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{7}
}
func (m *MsgSetEmergencyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetEmergencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetEmergencyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetEmergencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetEmergencyResponse.Merge(m, src)
}
func (m *MsgSetEmergencyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetEmergencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetEmergencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetEmergencyResponse proto.InternalMessageInfo

type MsgValidateRelease struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Id        uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgValidateRelease) Reset()         { *m = MsgValidateRelease{} }
func (m *MsgValidateRelease) String() string { return proto.CompactTextString(m) }
func (*MsgValidateRelease) ProtoMessage()    {}
func (*MsgValidateRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{8}
}
func (m *MsgValidateRelease) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgValidateRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgValidateRelease.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgValidateRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgValidateRelease.Merge(m, src)
}
func (m *MsgValidateRelease) XXX_Size() int {
	return m.Size()
}
func (m *MsgValidateRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgValidateRelease.DiscardUnknown(m)
}

var xxx_messageInfo_MsgValidateRelease proto.InternalMessageInfo

func (m *MsgValidateRelease) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgValidateRelease) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgValidateReleaseResponse struct {
}

func (m *MsgValidateReleaseResponse) Reset()         { *m = MsgValidateReleaseResponse{} }
func (m *MsgValidateReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgValidateReleaseResponse) ProtoMessage()    {}
func (*MsgValidateReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{9}
}
func (m *MsgValidateReleaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgValidateReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgValidateReleaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgValidateReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgValidateReleaseResponse.Merge(m, src)
}
func (m *MsgValidateReleaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgValidateReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgValidateReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgValidateReleaseResponse proto.InternalMessageInfo

type MsgRejectRelease struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Id        uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgRejectRelease) Reset()         { *m = MsgRejectRelease{} }
func (m *MsgRejectRelease) String() string { return proto.CompactTextString(m) }
func (*MsgRejectRelease) ProtoMessage()    {}
func (*MsgRejectRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{10}
}
func (m *MsgRejectRelease) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectRelease.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectRelease.Merge(m, src)
}
func (m *MsgRejectRelease) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectRelease.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectRelease proto.InternalMessageInfo

func (m *MsgRejectRelease) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRejectRelease) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgRejectReleaseResponse struct {
}

func (m *MsgRejectReleaseResponse) Reset()         { *m = MsgRejectReleaseResponse{} }
func (m *MsgRejectReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRejectReleaseResponse) ProtoMessage()    {}
func (*MsgRejectReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{11}
}
func (m *MsgRejectReleaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectReleaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectReleaseResponse.Merge(m, src)
}
func (m *MsgRejectReleaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectReleaseResponse proto.InternalMessageInfo

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{12}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4221d9a8ae5bdbc, []int{13}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgPublishRelease)(nil), "lumen.release.v1.MsgPublishRelease")
	proto.RegisterType((*MsgPublishReleaseResponse)(nil), "lumen.release.v1.MsgPublishReleaseResponse")
	proto.RegisterType((*MsgYankRelease)(nil), "lumen.release.v1.MsgYankRelease")
	proto.RegisterType((*MsgYankReleaseResponse)(nil), "lumen.release.v1.MsgYankReleaseResponse")
	proto.RegisterType((*MsgMirrorRelease)(nil), "lumen.release.v1.MsgMirrorRelease")
	proto.RegisterType((*MsgMirrorReleaseResponse)(nil), "lumen.release.v1.MsgMirrorReleaseResponse")
	proto.RegisterType((*MsgSetEmergency)(nil), "lumen.release.v1.MsgSetEmergency")
	proto.RegisterType((*MsgSetEmergencyResponse)(nil), "lumen.release.v1.MsgSetEmergencyResponse")
	proto.RegisterType((*MsgValidateRelease)(nil), "lumen.release.v1.MsgValidateRelease")
	proto.RegisterType((*MsgValidateReleaseResponse)(nil), "lumen.release.v1.MsgValidateReleaseResponse")
	proto.RegisterType((*MsgRejectRelease)(nil), "lumen.release.v1.MsgRejectRelease")
	proto.RegisterType((*MsgRejectReleaseResponse)(nil), "lumen.release.v1.MsgRejectReleaseResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "lumen.release.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "lumen.release.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("lumen/release/v1/tx.proto", fileDescriptor_e4221d9a8ae5bdbc) }

var fileDescriptor_e4221d9a8ae5bdbc = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4b, 0x6f, 0xd3, 0x5a,
	0x10, 0x8e, 0x93, 0xbe, 0x32, 0x6d, 0xd2, 0xd6, 0xea, 0xbd, 0x75, 0xac, 0xde, 0x34, 0x75, 0x2f,
	0x52, 0x48, 0x21, 0xa6, 0x41, 0x62, 0x51, 0x24, 0x24, 0x2a, 0xb1, 0x60, 0x61, 0x51, 0xb9, 0x14,
	0xa9, 0x08, 0x29, 0x72, 0xe2, 0x83, 0xeb, 0xd6, 0x8f, 0xe8, 0x9c, 0x93, 0x3e, 0x76, 0x88, 0x25,
	0x2b, 0x36, 0xfc, 0x05, 0x84, 0xc4, 0x26, 0x0b, 0x56, 0xfc, 0x82, 0x2e, 0x2b, 0x56, 0xac, 0x10,
	0x6a, 0x17, 0xfd, 0x1b, 0xc8, 0xcf, 0xf8, 0x55, 0xa5, 0x82, 0xb2, 0x89, 0x72, 0x66, 0xbe, 0x99,
	0xf9, 0x66, 0xce, 0xf9, 0xc6, 0x50, 0x31, 0xfa, 0x26, 0xb2, 0x44, 0x8c, 0x0c, 0xa4, 0x10, 0x24,
	0x1e, 0xae, 0x8b, 0xf4, 0xb8, 0xd9, 0xc3, 0x36, 0xb5, 0xd9, 0x39, 0xd7, 0xd5, 0xf4, 0x5d, 0xcd,
	0xc3, 0x75, 0x7e, 0x5e, 0x31, 0x75, 0xcb, 0x16, 0xdd, 0x5f, 0x0f, 0xc4, 0x2f, 0x76, 0x6d, 0x62,
	0xda, 0x44, 0x34, 0x89, 0xe6, 0x04, 0x9b, 0x44, 0xf3, 0x1d, 0x15, 0xcf, 0xd1, 0x76, 0x4f, 0xa2,
	0x77, 0xf0, 0x5d, 0x0b, 0x9a, 0xad, 0xd9, 0x9e, 0xdd, 0xf9, 0xe7, 0x5b, 0x97, 0xd2, 0x4c, 0x4e,
	0x7a, 0x28, 0x88, 0xf9, 0x2f, 0xe5, 0xed, 0x29, 0x58, 0x31, 0x7d, 0xb7, 0xf0, 0x81, 0x81, 0x79,
	0x89, 0x68, 0x5b, 0xfd, 0x8e, 0xa1, 0x93, 0x3d, 0xd9, 0x43, 0xb1, 0x2d, 0x98, 0xec, 0x62, 0xa4,
	0x50, 0x1b, 0x73, 0x4c, 0x8d, 0xa9, 0x17, 0x37, 0xb9, 0x6f, 0x5f, 0xee, 0x2e, 0xf8, 0x5c, 0x1e,
	0xab, 0x2a, 0x46, 0x84, 0x6c, 0x53, 0xac, 0x5b, 0x9a, 0x1c, 0x00, 0xd9, 0x47, 0x30, 0xe9, 0x17,
	0xe1, 0xf2, 0x35, 0xa6, 0x3e, 0xdd, 0xaa, 0x34, 0x93, 0x73, 0x68, 0xfa, 0xf9, 0x37, 0x8b, 0xa7,
	0x3f, 0x96, 0x73, 0x9f, 0x2e, 0x07, 0x0d, 0x46, 0x0e, 0x82, 0x36, 0x66, 0xde, 0x5e, 0x0e, 0x1a,
	0x41, 0x36, 0x61, 0x0d, 0x2a, 0x29, 0x5a, 0x32, 0x22, 0x3d, 0xdb, 0x22, 0x88, 0x2d, 0x43, 0x5e,
	0x57, 0x5d, 0x66, 0x63, 0x72, 0x5e, 0x57, 0x85, 0x0e, 0x94, 0x25, 0xa2, 0xed, 0x2a, 0xd6, 0xc1,
	0x9f, 0x34, 0xe0, 0x65, 0xcd, 0x07, 0x59, 0x13, 0x84, 0x38, 0xf8, 0x37, 0x5e, 0x23, 0x60, 0x23,
	0x7c, 0x64, 0x60, 0x4e, 0x22, 0x9a, 0xa4, 0x63, 0x6c, 0xe3, 0x1b, 0x24, 0xc0, 0xde, 0x82, 0xb2,
	0x82, 0xa9, 0xfe, 0x5a, 0xe9, 0xd2, 0xb6, 0x6e, 0xa9, 0xe8, 0x98, 0x2b, 0xd4, 0x98, 0x7a, 0x49,
	0x2e, 0x05, 0xd6, 0xa7, 0x8e, 0x91, 0xad, 0xc0, 0x94, 0x85, 0x8e, 0xda, 0x7d, 0x6c, 0x10, 0x6e,
	0xac, 0x56, 0xa8, 0x17, 0xe5, 0x49, 0x0b, 0x1d, 0xed, 0x60, 0x83, 0x24, 0x5a, 0xb8, 0x07, 0x5c,
	0x92, 0x67, 0x38, 0xd2, 0x05, 0x18, 0x57, 0x54, 0x15, 0x79, 0x53, 0x2d, 0xc9, 0xde, 0x41, 0xf8,
	0xcc, 0xc0, 0xac, 0x44, 0xb4, 0x6d, 0x44, 0x9f, 0x98, 0x08, 0x6b, 0xc8, 0xea, 0x9e, 0xdc, 0x48,
	0x67, 0x2b, 0x30, 0x83, 0x82, 0x84, 0x6d, 0xfb, 0xc0, 0xed, 0x6b, 0x4a, 0x9e, 0x0e, 0x6d, 0xcf,
	0x0e, 0xd8, 0x55, 0x28, 0x0d, 0x21, 0x94, 0x1a, 0xdc, 0x58, 0x8d, 0xa9, 0x17, 0xe4, 0x61, 0xdc,
	0x73, 0x6a, 0x24, 0xfa, 0xab, 0xc0, 0x62, 0x82, 0x6c, 0x78, 0x47, 0x06, 0xb0, 0x12, 0xd1, 0x5e,
	0x28, 0x86, 0xae, 0x2a, 0x14, 0x05, 0x97, 0xf4, 0x00, 0x8a, 0x4a, 0x9f, 0xee, 0xd9, 0x58, 0xa7,
	0x27, 0x23, 0x9b, 0x19, 0x42, 0x53, 0x2f, 0xa5, 0xec, 0xd0, 0x18, 0xfa, 0x85, 0x25, 0xe0, 0xd3,
	0xd5, 0x42, 0x2e, 0xfb, 0xee, 0x73, 0x91, 0xd1, 0x3e, 0xea, 0xd2, 0xbf, 0xcd, 0x84, 0x77, 0xaf,
	0x3c, 0x56, 0x2b, 0xe4, 0xf1, 0xd5, 0xbb, 0xdc, 0x9d, 0x9e, 0x43, 0x72, 0xcb, 0x5d, 0x0a, 0xbf,
	0xcd, 0xe3, 0x21, 0x4c, 0x78, 0x6b, 0xc5, 0xd7, 0x3e, 0x97, 0xd6, 0xbe, 0x57, 0x21, 0x2a, 0x7d,
	0x3f, 0x64, 0xa3, 0x15, 0x27, 0xfd, 0xee, 0x72, 0xd0, 0x58, 0xf6, 0xb6, 0xd6, 0x71, 0xb8, 0xb7,
	0x12, 0x44, 0xfd, 0xbb, 0x8e, 0x9a, 0x82, 0xbe, 0x5a, 0x83, 0x71, 0x28, 0x48, 0x44, 0x63, 0x3b,
	0x50, 0x4e, 0xac, 0xb5, 0xd5, 0x34, 0xab, 0xd4, 0x92, 0xe1, 0xd7, 0xae, 0x01, 0x0a, 0x65, 0xb3,
	0x0b, 0xd3, 0xd1, 0xb5, 0x53, 0xcb, 0x8c, 0x8d, 0x20, 0xf8, 0xfa, 0x28, 0x44, 0x98, 0xba, 0x0d,
	0xa5, 0xf8, 0x4a, 0x11, 0x32, 0x43, 0x63, 0x18, 0xbe, 0x31, 0x1a, 0x13, 0x16, 0x78, 0x05, 0x33,
	0x31, 0x61, 0xaf, 0x64, 0xc6, 0x46, 0x21, 0xfc, 0xed, 0x91, 0x90, 0x30, 0x3b, 0x82, 0xd9, 0xa4,
	0xdc, 0xfe, 0xcf, 0x8c, 0x4e, 0xa0, 0xf8, 0x3b, 0xd7, 0x41, 0x45, 0xa7, 0x14, 0x57, 0x52, 0xf6,
	0x94, 0x62, 0x98, 0x2b, 0xa6, 0x94, 0xa9, 0x12, 0x67, 0x4a, 0x31, 0x85, 0x64, 0x4f, 0x29, 0x0a,
	0xb9, 0x62, 0x4a, 0x59, 0x6f, 0x95, 0x1f, 0x7f, 0xe3, 0x28, 0x61, 0x53, 0x3c, 0x3d, 0xaf, 0x32,
	0x67, 0xe7, 0x55, 0xe6, 0xe7, 0x79, 0x95, 0x79, 0x7f, 0x51, 0xcd, 0x9d, 0x5d, 0x54, 0x73, 0xdf,
	0x2f, 0xaa, 0xb9, 0x97, 0xff, 0x24, 0x85, 0xe0, 0x7e, 0xdb, 0x3b, 0x13, 0xee, 0xd7, 0xfb, 0xfe,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x43, 0x68, 0x90, 0x86, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	PublishRelease(ctx context.Context, in *MsgPublishRelease, opts ...grpc.CallOption) (*MsgPublishReleaseResponse, error)
	YankRelease(ctx context.Context, in *MsgYankRelease, opts ...grpc.CallOption) (*MsgYankReleaseResponse, error)
	MirrorRelease(ctx context.Context, in *MsgMirrorRelease, opts ...grpc.CallOption) (*MsgMirrorReleaseResponse, error)
	SetEmergency(ctx context.Context, in *MsgSetEmergency, opts ...grpc.CallOption) (*MsgSetEmergencyResponse, error)
	ValidateRelease(ctx context.Context, in *MsgValidateRelease, opts ...grpc.CallOption) (*MsgValidateReleaseResponse, error)
	RejectRelease(ctx context.Context, in *MsgRejectRelease, opts ...grpc.CallOption) (*MsgRejectReleaseResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) PublishRelease(ctx context.Context, in *MsgPublishRelease, opts ...grpc.CallOption) (*MsgPublishReleaseResponse, error) {
	out := new(MsgPublishReleaseResponse)
	err := c.cc.Invoke(ctx, "/lumen.release.v1.Msg/PublishRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) YankRelease(ctx context.Context, in *MsgYankRelease, opts ...grpc.CallOption) (*MsgYankReleaseResponse, error) {
	out := new(MsgYankReleaseResponse)
	err := c.cc.Invoke(ctx, "/lumen.release.v1.Msg/YankRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MirrorRelease(ctx context.Context, in *MsgMirrorRelease, opts ...grpc.CallOption) (*MsgMirrorReleaseResponse, error) {
	out := new(MsgMirrorReleaseResponse)
	err := c.cc.Invoke(ctx, "/lumen.release.v1.Msg/MirrorRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetEmergency(ctx context.Context, in *MsgSetEmergency, opts ...grpc.CallOption) (*MsgSetEmergencyResponse, error) {
	out := new(MsgSetEmergencyResponse)
	err := c.cc.Invoke(ctx, "/lumen.release.v1.Msg/SetEmergency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ValidateRelease(ctx context.Context, in *MsgValidateRelease, opts ...grpc.CallOption) (*MsgValidateReleaseResponse, error) {
	out := new(MsgValidateReleaseResponse)
	err := c.cc.Invoke(ctx, "/lumen.release.v1.Msg/ValidateRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectRelease(ctx context.Context, in *MsgRejectRelease, opts ...grpc.CallOption) (*MsgRejectReleaseResponse, error) {
	out := new(MsgRejectReleaseResponse)
	err := c.cc.Invoke(ctx, "/lumen.release.v1.Msg/RejectRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/lumen.release.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	PublishRelease(context.Context, *MsgPublishRelease) (*MsgPublishReleaseResponse, error)
	YankRelease(context.Context, *MsgYankRelease) (*MsgYankReleaseResponse, error)
	MirrorRelease(context.Context, *MsgMirrorRelease) (*MsgMirrorReleaseResponse, error)
	SetEmergency(context.Context, *MsgSetEmergency) (*MsgSetEmergencyResponse, error)
	ValidateRelease(context.Context, *MsgValidateRelease) (*MsgValidateReleaseResponse, error)
	RejectRelease(context.Context, *MsgRejectRelease) (*MsgRejectReleaseResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) PublishRelease(ctx context.Context, req *MsgPublishRelease) (*MsgPublishReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishRelease not implemented")
}
func (*UnimplementedMsgServer) YankRelease(ctx context.Context, req *MsgYankRelease) (*MsgYankReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method YankRelease not implemented")
}
func (*UnimplementedMsgServer) MirrorRelease(ctx context.Context, req *MsgMirrorRelease) (*MsgMirrorReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MirrorRelease not implemented")
}
func (*UnimplementedMsgServer) SetEmergency(ctx context.Context, req *MsgSetEmergency) (*MsgSetEmergencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEmergency not implemented")
}
func (*UnimplementedMsgServer) ValidateRelease(ctx context.Context, req *MsgValidateRelease) (*MsgValidateReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRelease not implemented")
}
func (*UnimplementedMsgServer) RejectRelease(ctx context.Context, req *MsgRejectRelease) (*MsgRejectReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectRelease not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_PublishRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPublishRelease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PublishRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.release.v1.Msg/PublishRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PublishRelease(ctx, req.(*MsgPublishRelease))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_YankRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgYankRelease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).YankRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.release.v1.Msg/YankRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).YankRelease(ctx, req.(*MsgYankRelease))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MirrorRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMirrorRelease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MirrorRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.release.v1.Msg/MirrorRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MirrorRelease(ctx, req.(*MsgMirrorRelease))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetEmergency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetEmergency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetEmergency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.release.v1.Msg/SetEmergency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetEmergency(ctx, req.(*MsgSetEmergency))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ValidateRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgValidateRelease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ValidateRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.release.v1.Msg/ValidateRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ValidateRelease(ctx, req.(*MsgValidateRelease))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRejectRelease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.release.v1.Msg/RejectRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectRelease(ctx, req.(*MsgRejectRelease))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumen.release.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lumen.release.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishRelease",
			Handler:    _Msg_PublishRelease_Handler,
		},
		{
			MethodName: "YankRelease",
			Handler:    _Msg_YankRelease_Handler,
		},
		{
			MethodName: "MirrorRelease",
			Handler:    _Msg_MirrorRelease_Handler,
		},
		{
			MethodName: "SetEmergency",
			Handler:    _Msg_SetEmergency_Handler,
		},
		{
			MethodName: "ValidateRelease",
			Handler:    _Msg_ValidateRelease_Handler,
		},
		{
			MethodName: "RejectRelease",
			Handler:    _Msg_RejectRelease_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lumen/release/v1/tx.proto",
}

func (m *MsgPublishRelease) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPublishRelease) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPublishRelease) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Release.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPublishReleaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPublishReleaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPublishReleaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgYankRelease) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgYankRelease) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgYankRelease) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgYankReleaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgYankReleaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgYankReleaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMirrorRelease) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMirrorRelease) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMirrorRelease) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewUrls) > 0 {
		for iNdEx := len(m.NewUrls) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.NewUrls[iNdEx])
			copy(dAtA[i:], m.NewUrls[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.NewUrls[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ArtifactIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ArtifactIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMirrorReleaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMirrorReleaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMirrorReleaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Added != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Added))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetEmergency) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetEmergency) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetEmergency) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EmergencyTtl != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EmergencyTtl))
		i--
		dAtA[i] = 0x20
	}
	if m.EmergencyOk {
		i--
		if m.EmergencyOk {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetEmergencyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetEmergencyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetEmergencyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgValidateRelease) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgValidateRelease) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgValidateRelease) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgValidateReleaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgValidateReleaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgValidateReleaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRejectRelease) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectRelease) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectRelease) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRejectReleaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectReleaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectReleaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgPublishRelease) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Release.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgPublishReleaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgYankRelease) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgYankReleaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMirrorRelease) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if m.ArtifactIndex != 0 {
		n += 1 + sovTx(uint64(m.ArtifactIndex))
	}
	if len(m.NewUrls) > 0 {
		for _, s := range m.NewUrls {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgMirrorReleaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Added != 0 {
		n += 1 + sovTx(uint64(m.Added))
	}
	return n
}

func (m *MsgSetEmergency) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if m.EmergencyOk {
		n += 2
	}
	if m.EmergencyTtl != 0 {
		n += 1 + sovTx(uint64(m.EmergencyTtl))
	}
	return n
}

func (m *MsgSetEmergencyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgValidateRelease) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgValidateReleaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRejectRelease) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgRejectReleaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgPublishRelease) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPublishRelease: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPublishRelease: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Release", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Release.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPublishReleaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPublishReleaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPublishReleaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgYankRelease) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgYankRelease: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgYankRelease: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgYankReleaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgYankReleaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgYankReleaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMirrorRelease) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMirrorRelease: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMirrorRelease: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArtifactIndex", wireType)
			}
			m.ArtifactIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ArtifactIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewUrls", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewUrls = append(m.NewUrls, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMirrorReleaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMirrorReleaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMirrorReleaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Added", wireType)
			}
			m.Added = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Added |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetEmergency) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetEmergency: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetEmergency: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyOk", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EmergencyOk = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyTtl", wireType)
			}
			m.EmergencyTtl = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmergencyTtl |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetEmergencyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetEmergencyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetEmergencyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgValidateRelease) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgValidateRelease: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgValidateRelease: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgValidateReleaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgValidateReleaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgValidateReleaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectRelease) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectRelease: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectRelease: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectReleaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectReleaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectReleaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
