// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumen/release/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	AllowedPublishers          []string `protobuf:"bytes,1,rep,name=allowed_publishers,json=allowedPublishers,proto3" json:"allowed_publishers,omitempty"`
	Channels                   []string `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	MaxArtifacts               uint32   `protobuf:"varint,3,opt,name=max_artifacts,json=maxArtifacts,proto3" json:"max_artifacts,omitempty"`
	MaxUrlsPerArt              uint32   `protobuf:"varint,4,opt,name=max_urls_per_art,json=maxUrlsPerArt,proto3" json:"max_urls_per_art,omitempty"`
	MaxSigsPerArt              uint32   `protobuf:"varint,5,opt,name=max_sigs_per_art,json=maxSigsPerArt,proto3" json:"max_sigs_per_art,omitempty"`
	MaxNotesLen                uint32   `protobuf:"varint,6,opt,name=max_notes_len,json=maxNotesLen,proto3" json:"max_notes_len,omitempty"`
	PublishFeeUlmn             uint64   `protobuf:"varint,7,opt,name=publish_fee_ulmn,json=publishFeeUlmn,proto3" json:"publish_fee_ulmn,omitempty"`
	MaxPendingTtl              uint64   `protobuf:"varint,8,opt,name=max_pending_ttl,json=maxPendingTtl,proto3" json:"max_pending_ttl,omitempty"`
	DaoPublishers              []string `protobuf:"bytes,9,rep,name=dao_publishers,json=daoPublishers,proto3" json:"dao_publishers,omitempty"`
	RejectRefundBps            uint32   `protobuf:"varint,10,opt,name=reject_refund_bps,json=rejectRefundBps,proto3" json:"reject_refund_bps,omitempty"`
	RequireValidationForStable bool     `protobuf:"varint,11,opt,name=require_validation_for_stable,json=requireValidationForStable,proto3" json:"require_validation_for_stable,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_963f740ed0765578, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAllowedPublishers() []string {
	if m != nil {
		return m.AllowedPublishers
	}
	return nil
}

func (m *Params) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *Params) GetMaxArtifacts() uint32 {
	if m != nil {
		return m.MaxArtifacts
	}
	return 0
}

func (m *Params) GetMaxUrlsPerArt() uint32 {
	if m != nil {
		return m.MaxUrlsPerArt
	}
	return 0
}

func (m *Params) GetMaxSigsPerArt() uint32 {
	if m != nil {
		return m.MaxSigsPerArt
	}
	return 0
}

func (m *Params) GetMaxNotesLen() uint32 {
	if m != nil {
		return m.MaxNotesLen
	}
	return 0
}

func (m *Params) GetPublishFeeUlmn() uint64 {
	if m != nil {
		return m.PublishFeeUlmn
	}
	return 0
}

func (m *Params) GetMaxPendingTtl() uint64 {
	if m != nil {
		return m.MaxPendingTtl
	}
	return 0
}

func (m *Params) GetDaoPublishers() []string {
	if m != nil {
		return m.DaoPublishers
	}
	return nil
}

func (m *Params) GetRejectRefundBps() uint32 {
	if m != nil {
		return m.RejectRefundBps
	}
	return 0
}

func (m *Params) GetRequireValidationForStable() bool {
	if m != nil {
		return m.RequireValidationForStable
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "lumen.release.v1.Params")
}

func init() { proto.RegisterFile("lumen/release/v1/params.proto", fileDescriptor_963f740ed0765578) }

var fileDescriptor_963f740ed0765578 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0x3a, 0x4a, 0xe7, 0xd1, 0xad, 0xb5, 0x00, 0x59, 0x95, 0x96, 0x55, 0x43, 0x40,
	0x34, 0x89, 0x46, 0x13, 0x37, 0x6e, 0xdd, 0x61, 0x27, 0x84, 0xaa, 0x8c, 0x71, 0xe0, 0x62, 0xb9,
	0xcd, 0x6b, 0x66, 0xe4, 0xd8, 0xc6, 0x76, 0x4a, 0xf9, 0x0a, 0x9c, 0xf8, 0x08, 0x7c, 0x04, 0x3e,
	0x06, 0xc7, 0x1d, 0x39, 0xa2, 0xf6, 0x00, 0xdf, 0x80, 0x2b, 0x8a, 0x93, 0x86, 0x8a, 0x4b, 0xf4,
	0xf2, 0xff, 0xff, 0xde, 0x7b, 0xf6, 0xf3, 0x43, 0xc7, 0xa2, 0xc8, 0x41, 0xc6, 0x06, 0x04, 0x30,
	0x0b, 0xf1, 0xf2, 0x3c, 0xd6, 0xcc, 0xb0, 0xdc, 0x8e, 0xb5, 0x51, 0x4e, 0xe1, 0xbe, 0xb7, 0xc7,
	0xb5, 0x3d, 0x5e, 0x9e, 0x0f, 0x07, 0x2c, 0xe7, 0x52, 0xc5, 0xfe, 0x5b, 0x41, 0xc3, 0x07, 0x99,
	0xca, 0x94, 0x0f, 0xe3, 0x32, 0xaa, 0xd4, 0xd3, 0x3f, 0x6d, 0xd4, 0x99, 0xfa, 0x5a, 0xf8, 0x39,
	0xc2, 0x4c, 0x08, 0xf5, 0x11, 0x52, 0xaa, 0x8b, 0x99, 0xe0, 0xf6, 0x06, 0x8c, 0x25, 0xc1, 0xa8,
	0x1d, 0xed, 0x27, 0x83, 0xda, 0x99, 0x36, 0x06, 0x1e, 0xa2, 0xee, 0xfc, 0x86, 0x49, 0x09, 0xc2,
	0x92, 0x3b, 0x1e, 0x6a, 0xfe, 0xf1, 0x63, 0xd4, 0xcb, 0xd9, 0x8a, 0x32, 0xe3, 0xf8, 0x82, 0xcd,
	0x9d, 0x25, 0xed, 0x51, 0x10, 0xf5, 0x92, 0xfb, 0x39, 0x5b, 0x4d, 0xb6, 0x1a, 0x7e, 0x86, 0xfa,
	0x25, 0x54, 0x18, 0x61, 0xa9, 0x06, 0x53, 0xd2, 0x64, 0xcf, 0x73, 0x65, 0xf2, 0xb5, 0x11, 0x76,
	0x0a, 0x66, 0x62, 0xdc, 0x16, 0xb4, 0x3c, 0xfb, 0x07, 0xde, 0x6d, 0xc0, 0x2b, 0x9e, 0x6d, 0xc1,
	0xd3, 0xaa, 0xad, 0x54, 0x0e, 0x2c, 0x15, 0x20, 0x49, 0xc7, 0x53, 0x07, 0x39, 0x5b, 0xbd, 0x2e,
	0xb5, 0x57, 0x20, 0x71, 0x84, 0xfa, 0xf5, 0xed, 0xe8, 0x02, 0x80, 0x16, 0x22, 0x97, 0xe4, 0xde,
	0x28, 0x88, 0xf6, 0x92, 0xc3, 0x5a, 0xbf, 0x04, 0xb8, 0x16, 0xb9, 0xc4, 0x4f, 0xd1, 0x51, 0x59,
	0x4d, 0x83, 0x4c, 0xb9, 0xcc, 0xa8, 0x73, 0x82, 0x74, 0x3d, 0x58, 0x36, 0x99, 0x56, 0xea, 0x1b,
	0x27, 0xf0, 0x13, 0x74, 0x98, 0x32, 0xb5, 0x3b, 0xb3, 0x7d, 0x3f, 0x8e, 0x5e, 0xca, 0xd4, 0xce,
	0xbc, 0xce, 0xd0, 0xc0, 0xc0, 0x7b, 0x98, 0x3b, 0x6a, 0x60, 0x51, 0xc8, 0x94, 0xce, 0xb4, 0x25,
	0xc8, 0x1f, 0xf0, 0xa8, 0x32, 0x12, 0xaf, 0x5f, 0x68, 0x8b, 0x27, 0xe8, 0xd8, 0xc0, 0x87, 0x82,
	0x1b, 0xa0, 0x4b, 0x26, 0x78, 0xca, 0x1c, 0x57, 0x92, 0x2e, 0x94, 0xa1, 0xd6, 0xb1, 0x99, 0x00,
	0x72, 0x30, 0x0a, 0xa2, 0x6e, 0x32, 0xac, 0xa1, 0xb7, 0x0d, 0x73, 0xa9, 0xcc, 0x95, 0x27, 0x5e,
	0x9e, 0xfc, 0xfe, 0x7a, 0x12, 0x7c, 0xfe, 0xf5, 0xed, 0xec, 0x51, 0xb5, 0x3b, 0xab, 0x66, 0x7b,
	0xaa, 0xe7, 0xbe, 0x88, 0xbf, 0xaf, 0xc3, 0xe0, 0x76, 0x1d, 0x06, 0x3f, 0xd7, 0x61, 0xf0, 0x65,
	0x13, 0xb6, 0x6e, 0x37, 0x61, 0xeb, 0xc7, 0x26, 0x6c, 0xbd, 0x7b, 0xf8, 0x7f, 0x86, 0xfb, 0xa4,
	0xc1, 0xce, 0x3a, 0x7e, 0x63, 0x5e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xca, 0x4e, 0x0b, 0xb0,
	0x8d, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.AllowedPublishers) != len(that1.AllowedPublishers) {
		return false
	}
	for i := range this.AllowedPublishers {
		if this.AllowedPublishers[i] != that1.AllowedPublishers[i] {
			return false
		}
	}
	if len(this.Channels) != len(that1.Channels) {
		return false
	}
	for i := range this.Channels {
		if this.Channels[i] != that1.Channels[i] {
			return false
		}
	}
	if this.MaxArtifacts != that1.MaxArtifacts {
		return false
	}
	if this.MaxUrlsPerArt != that1.MaxUrlsPerArt {
		return false
	}
	if this.MaxSigsPerArt != that1.MaxSigsPerArt {
		return false
	}
	if this.MaxNotesLen != that1.MaxNotesLen {
		return false
	}
	if this.PublishFeeUlmn != that1.PublishFeeUlmn {
		return false
	}
	if this.MaxPendingTtl != that1.MaxPendingTtl {
		return false
	}
	if len(this.DaoPublishers) != len(that1.DaoPublishers) {
		return false
	}
	for i := range this.DaoPublishers {
		if this.DaoPublishers[i] != that1.DaoPublishers[i] {
			return false
		}
	}
	if this.RejectRefundBps != that1.RejectRefundBps {
		return false
	}
	if this.RequireValidationForStable != that1.RequireValidationForStable {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequireValidationForStable {
		i--
		if m.RequireValidationForStable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.RejectRefundBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RejectRefundBps))
		i--
		dAtA[i] = 0x50
	}
	if len(m.DaoPublishers) > 0 {
		for iNdEx := len(m.DaoPublishers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.DaoPublishers[iNdEx])
			copy(dAtA[i:], m.DaoPublishers[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.DaoPublishers[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.MaxPendingTtl != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPendingTtl))
		i--
		dAtA[i] = 0x40
	}
	if m.PublishFeeUlmn != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PublishFeeUlmn))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxNotesLen != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxNotesLen))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxSigsPerArt != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSigsPerArt))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxUrlsPerArt != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxUrlsPerArt))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxArtifacts != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxArtifacts))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Channels) > 0 {
		for iNdEx := len(m.Channels) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Channels[iNdEx])
			copy(dAtA[i:], m.Channels[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.Channels[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.AllowedPublishers) > 0 {
		for iNdEx := len(m.AllowedPublishers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedPublishers[iNdEx])
			copy(dAtA[i:], m.AllowedPublishers[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AllowedPublishers[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AllowedPublishers) > 0 {
		for _, s := range m.AllowedPublishers {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.Channels) > 0 {
		for _, s := range m.Channels {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.MaxArtifacts != 0 {
		n += 1 + sovParams(uint64(m.MaxArtifacts))
	}
	if m.MaxUrlsPerArt != 0 {
		n += 1 + sovParams(uint64(m.MaxUrlsPerArt))
	}
	if m.MaxSigsPerArt != 0 {
		n += 1 + sovParams(uint64(m.MaxSigsPerArt))
	}
	if m.MaxNotesLen != 0 {
		n += 1 + sovParams(uint64(m.MaxNotesLen))
	}
	if m.PublishFeeUlmn != 0 {
		n += 1 + sovParams(uint64(m.PublishFeeUlmn))
	}
	if m.MaxPendingTtl != 0 {
		n += 1 + sovParams(uint64(m.MaxPendingTtl))
	}
	if len(m.DaoPublishers) > 0 {
		for _, s := range m.DaoPublishers {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.RejectRefundBps != 0 {
		n += 1 + sovParams(uint64(m.RejectRefundBps))
	}
	if m.RequireValidationForStable {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedPublishers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedPublishers = append(m.AllowedPublishers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channels", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channels = append(m.Channels, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxArtifacts", wireType)
			}
			m.MaxArtifacts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxArtifacts |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxUrlsPerArt", wireType)
			}
			m.MaxUrlsPerArt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxUrlsPerArt |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSigsPerArt", wireType)
			}
			m.MaxSigsPerArt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSigsPerArt |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNotesLen", wireType)
			}
			m.MaxNotesLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNotesLen |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublishFeeUlmn", wireType)
			}
			m.PublishFeeUlmn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PublishFeeUlmn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingTtl", wireType)
			}
			m.MaxPendingTtl = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingTtl |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoPublishers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DaoPublishers = append(m.DaoPublishers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectRefundBps", wireType)
			}
			m.RejectRefundBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectRefundBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequireValidationForStable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequireValidationForStable = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
